"""CarryOn™ — Estate Guardian PDF Export Routes

Extracted from guardian.py for maintainability.
All PDF generation endpoints for IAC checklists, to-do lists, IAC reports,
conversation transcripts, plans of action, and beneficiary checklists.
"""

import asyncio
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, Response
from pydantic import BaseModel as PydanticBaseModel

from config import XAI_MODEL, db, logger, xai_client
from services.audit import audit_log
from utils import get_current_user

router = APIRouter()


async def _get_user_estate(current_user: dict, projection: dict | None = None):
    """Get the first estate for a user, with admin fallback (all estates)."""
    proj = projection or {"_id": 0}
    if current_user.get("role") == "admin":
        return await db.estates.find({}, proj).to_list(1)
    return await db.estates.find({"owner_id": current_user["id"]}, proj).to_list(1)


def sanitize_for_pdf(text: str) -> str:
    """Sanitize text for PDF by replacing Unicode characters with ASCII equivalents."""
    if not text:
        return ""
    # Common Unicode replacements
    replacements = {
        "\u2014": "-",  # em-dash
        "\u2013": "-",  # en-dash
        "\u2018": "'",  # left single quote
        "\u2019": "'",  # right single quote
        "\u201c": '"',  # left double quote
        "\u201d": '"',  # right double quote
        "\u2026": "...",  # ellipsis
        "\u2022": "*",  # bullet
        "\u00a0": " ",  # non-breaking space
        "\u200b": "",  # zero-width space
    }
    for unicode_char, ascii_char in replacements.items():
        text = text.replace(unicode_char, ascii_char)
    # Remove any remaining non-ASCII characters
    return text.encode("ascii", "replace").decode("ascii")


@router.post("/guardian/export-checklist")
async def export_checklist_pdf(
    current_user: dict = Depends(get_current_user),
):
    """Generate a printable PDF checklist from the user's estate checklist items."""
    from services.pdf_trust_footer import CarryOnPDF

    # Get user's estate
    estates = await _get_user_estate(current_user)
    if not estates:
        raise HTTPException(status_code=404, detail="No estate found")

    estate = estates[0]
    estate_id = estate["id"]

    # Get checklist items
    items = await db.checklists.find({"estate_id": estate_id}, {"_id": 0}).sort("order", 1).to_list(200)

    if not items:
        raise HTTPException(status_code=404, detail="No checklist items found")

    # Get readiness data
    from services.readiness import calculate_estate_readiness

    readiness = await calculate_estate_readiness(estate_id)

    # Build PDF
    pdf = CarryOnPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Get benefactor's state of residence
    benefactor = await db.users.find_one(
        {"id": estate.get("owner_id")},
        {"_id": 0, "id": 1, "address_state": 1},
    )
    user_state = (benefactor or {}).get("address_state") or estate.get("state") or "Not specified"

    # Header
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(212, 175, 55)
    pdf.cell(0, 12, "CarryOn Estate Guardian", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, "Immediate Action Checklist", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(
        0,
        5,
        sanitize_for_pdf(
            f"Estate: {estate['name']}  |  State: {user_state}  |  Readiness: {readiness['overall_score']}%"
        ),
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.cell(
        0,
        5,
        f"Generated: {datetime.now(timezone.utc).strftime('%B %d, %Y at %I:%M %p UTC')}",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.ln(3)

    # State jurisdiction banner
    pdf.set_fill_color(15, 29, 53)
    pdf.set_draw_color(212, 175, 55)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(212, 175, 55)
    jurisdiction_text = (
        f"Declared State of Residence: {user_state}  |  "
        f"This checklist is informed by {user_state} estate planning statutes and probate rules."
    )
    pdf.multi_cell(0, 4.5, sanitize_for_pdf(jurisdiction_text), border=1, fill=True, align="C")
    pdf.ln(3)

    # Legal disclaimer box
    pdf.set_fill_color(255, 248, 220)
    pdf.set_draw_color(212, 175, 55)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(80, 80, 80)
    disclaimer = (
        "IMPORTANT: This checklist is generated by an AI assistant for informational purposes only and does not constitute legal advice. "
        "CarryOn Estate Guardian is not a licensed attorney. For legally binding decisions, always consult a bar-certified "
        "attorney licensed in your jurisdiction. No attorney-client relationship is created by using this service."
    )
    pdf.multi_cell(0, 3.5, disclaimer, border=1, fill=True)
    pdf.ln(6)

    # Separate items into two major sections
    beneficiary_items = [i for i in items if i.get("section") != "benefactor_recommendation"]
    benefactor_items = [i for i in items if i.get("section") == "benefactor_recommendation"]

    category_labels = {
        "immediate": "Immediate (Days 1-3)",
        "first_week": "First Week",
        "two_weeks": "Within Two Weeks",
        "first_month": "First Month",
        "legal": "Legal",
        "financial": "Financial",
        "insurance": "Insurance",
        "property": "Property",
        "medical": "Medical",
        "personal": "Personal",
        "government": "Government",
        "general": "General",
    }

    def render_items_by_category(pdf_obj, item_list):
        """Render a list of checklist items grouped by category."""
        cats = {}
        for item in item_list:
            cat = item.get("category", item.get("due_timeframe", "general"))
            if cat not in cats:
                cats[cat] = []
            cats[cat].append(item)

        for cat, cat_items in cats.items():
            pdf_obj.set_font("Helvetica", "B", 11)
            pdf_obj.set_text_color(30, 40, 70)
            pdf_obj.cell(
                0,
                7,
                category_labels.get(cat, cat.replace("_", " ").title()),
                new_x="LMARGIN",
                new_y="NEXT",
            )
            pdf_obj.set_draw_color(212, 175, 55)
            pdf_obj.line(pdf_obj.get_x(), pdf_obj.get_y(), pdf_obj.get_x() + 170, pdf_obj.get_y())
            pdf_obj.ln(3)

            for item in cat_items:
                check = "[x]" if item.get("is_completed") else "[ ]"
                pdf_obj.set_font("Helvetica", "B", 9)
                pdf_obj.set_text_color(40, 40, 40)
                pdf_obj.cell(8, 5, check)
                pdf_obj.cell(
                    0,
                    5,
                    sanitize_for_pdf(item["title"][:80]),
                    new_x="LMARGIN",
                    new_y="NEXT",
                )
                if item.get("description"):
                    pdf_obj.set_x(pdf_obj.get_x() + 8)
                    pdf_obj.set_font("Helvetica", "", 8)
                    pdf_obj.set_text_color(100, 100, 100)
                    pdf_obj.multi_cell(162, 4, sanitize_for_pdf(item["description"][:200]))
                if item.get("contact_name") or item.get("contact_phone"):
                    pdf_obj.set_x(pdf_obj.get_x() + 8)
                    pdf_obj.set_font("Helvetica", "I", 7)
                    pdf_obj.set_text_color(120, 120, 120)
                    contact = f"Contact: {item.get('contact_name', '')}"
                    if item.get("contact_phone"):
                        contact += f" | {item['contact_phone']}"
                    pdf_obj.cell(0, 4, sanitize_for_pdf(contact), new_x="LMARGIN", new_y="NEXT")
                pdf_obj.ln(2)

    # ── Section 1: Beneficiary Actions ──
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(34, 201, 147)
    pdf.cell(0, 9, "SECTION 1: Immediate Action Checklist for Beneficiaries", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(
        0,
        5,
        "Actions for your loved ones to execute after your passing.",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.ln(3)

    if beneficiary_items:
        render_items_by_category(pdf, beneficiary_items)
    else:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(120, 120, 120)
        pdf.cell(0, 6, "No beneficiary action items found.", new_x="LMARGIN", new_y="NEXT")

    # ── Section 2: Benefactor Recommendations ──
    if benefactor_items:
        pdf.ln(6)
        pdf.set_draw_color(212, 175, 55)
        pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 170, pdf.get_y())
        pdf.ln(4)
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(59, 130, 246)
        pdf.cell(0, 9, "SECTION 2: Estate Strengthening Recommendations", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(
            0,
            5,
            "Actions for YOU (the benefactor) to take now to improve your estate plan.",
            new_x="LMARGIN",
            new_y="NEXT",
        )
        pdf.ln(3)
        render_items_by_category(pdf, benefactor_items)

    # Summary footer
    completed = sum(1 for i in items if i.get("is_completed"))
    pdf.ln(6)
    pdf.set_draw_color(200, 200, 200)
    pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 170, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(30, 40, 70)
    pdf.cell(
        0,
        6,
        f"Progress: {completed}/{len(items)} items completed ({int(completed / len(items) * 100) if items else 0}%)",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(
        0,
        5,
        "AES-256-GCM Encrypted  |  Zero-Knowledge Architecture  |  2FA Protected",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.cell(
        0,
        5,
        f"CarryOn Technologies  |  carryon.us  |  {datetime.now(timezone.utc).year}",
        new_x="LMARGIN",
        new_y="NEXT",
    )

    # Return PDF
    pdf_bytes = bytes(pdf.output())
    await audit_log(
        action="guardian.checklist_export",
        user_id=current_user["id"],
        resource_type="checklist_pdf",
        estate_id=estate_id,
        details={"items": len(items), "completed": completed},
    )

    return Response(
        content=bytes(pdf_bytes),
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="CarryOn_IAC_{datetime.now(timezone.utc).strftime("%Y%m%d")}.pdf"'
        },
    )


class TodoExportRequest(PydanticBaseModel):
    content: str


@router.post("/guardian/export-todo")
async def export_todo_pdf(
    data: TodoExportRequest,
    current_user: dict = Depends(get_current_user),
):
    """Generate a PDF from the AI-generated to-do list text content."""
    from services.pdf_trust_footer import CarryOnPDF

    # Get user's estate for context
    estates = await _get_user_estate(current_user)
    estate_name = estates[0]["name"] if estates else "My Estate"
    estate_id = estates[0]["id"] if estates else None

    benefactor = await db.users.find_one({"id": current_user["id"]}, {"_id": 0, "id": 1, "address_state": 1})
    user_state = (benefactor or {}).get("address_state") or "Not specified"

    pdf = CarryOnPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Header
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(212, 175, 55)
    pdf.cell(0, 12, "CarryOn Estate Guardian", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, "Estate Strengthening To-Do List", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(
        0,
        5,
        sanitize_for_pdf(f"Estate: {estate_name}  |  State: {user_state}"),
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.cell(
        0,
        5,
        f"Generated: {datetime.now(timezone.utc).strftime('%B %d, %Y at %I:%M %p UTC')}",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.ln(3)

    # Legal disclaimer
    pdf.set_fill_color(255, 248, 220)
    pdf.set_draw_color(212, 175, 55)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(80, 80, 80)
    disclaimer = (
        "IMPORTANT: This to-do list is generated by an AI assistant for informational purposes only "
        "and does not constitute legal advice. For legally binding decisions, always consult a "
        "bar-certified attorney licensed in your jurisdiction."
    )
    pdf.multi_cell(0, 3.5, disclaimer, border=1, fill=True)
    pdf.ln(6)

    # Content — strip the legal disclaimer that's appended to every AI response
    content = data.content
    if "---\n*This analysis" in content:
        content = content[: content.index("---\n*This analysis")].strip()

    # Render content line by line
    left_margin = pdf.l_margin
    for line in content.split("\n"):
        clean = sanitize_for_pdf(line.strip())
        if not clean:
            pdf.ln(2)
            continue

        # Reset x position at start of each line to avoid FPDF width issues
        pdf.set_x(left_margin)

        # Detect headers (markdown ## or **)
        if clean.startswith("##") or clean.startswith("**"):
            heading = clean.lstrip("#* ").rstrip("*")
            if heading:
                pdf.set_font("Helvetica", "B", 11)
                pdf.set_text_color(30, 40, 70)
                pdf.multi_cell(0, 5.5, heading)
                pdf.set_draw_color(212, 175, 55)
                pdf.line(left_margin, pdf.get_y(), left_margin + 170, pdf.get_y())
                pdf.ln(2)
        elif clean.startswith(("- ", "* ", "- [ ]", "- [x]")):
            # Bullet/checklist items
            bullet_text = clean.lstrip("-*[] x").strip()
            if bullet_text:
                check = "[x]" if "[x]" in clean else "[ ]" if "[ ]" in clean else "-"
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(40, 40, 40)
                pdf.cell(8, 5, check, new_x="RIGHT", new_y="TOP")
                pdf.multi_cell(0, 5, bullet_text)
        elif clean[0].isdigit() and "." in clean[:4]:
            # Numbered items
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(40, 40, 40)
            pdf.multi_cell(0, 5, clean)
        else:
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(60, 60, 60)
            pdf.multi_cell(0, 4.5, clean)

    # Footer
    pdf.ln(6)
    pdf.set_draw_color(200, 200, 200)
    pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 170, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(
        0,
        5,
        "AES-256-GCM Encrypted  |  Zero-Knowledge Architecture  |  2FA Protected",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.cell(
        0,
        5,
        f"CarryOn Technologies  |  carryon.us  |  {datetime.now(timezone.utc).year}",
        new_x="LMARGIN",
        new_y="NEXT",
    )

    pdf_bytes = bytes(pdf.output())
    if estate_id:
        await audit_log(
            action="guardian.todo_export",
            user_id=current_user["id"],
            resource_type="todo_pdf",
            estate_id=estate_id,
            details={"content_length": len(data.content)},
        )

    return Response(
        content=bytes(pdf_bytes),
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="CarryOn_ToDo_{datetime.now(timezone.utc).strftime("%Y%m%d")}.pdf"'
        },
    )


class IacReportRequest(PydanticBaseModel):
    content: str


@router.post("/guardian/export-iac-report")
async def export_iac_report_pdf(
    data: IacReportRequest,
    current_user: dict = Depends(get_current_user),
):
    """Generate a two-section IAC Report PDF from the AI-generated IAC response.

    Section 1: Immediate Action Checklist for Beneficiaries (post-death instructions).
    Section 2: Estate Strengthening Recommendations for the Benefactor (to-do now).
    """
    from services.pdf_trust_footer import CarryOnPDF

    estates = await _get_user_estate(current_user)
    estate_name = estates[0]["name"] if estates else "My Estate"
    estate_id = estates[0]["id"] if estates else None

    benefactor = await db.users.find_one(
        {"id": current_user["id"]},
        {"_id": 0, "id": 1, "name": 1, "address_state": 1},
    )
    user_name = (benefactor or {}).get("name", "Benefactor")
    user_state = (benefactor or {}).get("address_state") or "Not specified"

    pdf = CarryOnPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Header
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(212, 175, 55)
    pdf.cell(0, 12, "CarryOn Estate Guardian", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(30, 40, 70)
    pdf.cell(0, 7, "Immediate Action Checklist Report", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(
        0,
        5,
        sanitize_for_pdf(f"Prepared for: {user_name}  |  Estate: {estate_name}  |  State: {user_state}"),
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.cell(
        0,
        5,
        f"Generated: {datetime.now(timezone.utc).strftime('%B %d, %Y at %I:%M %p UTC')}",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.ln(3)

    # State jurisdiction banner
    pdf.set_fill_color(15, 29, 53)
    pdf.set_draw_color(212, 175, 55)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(212, 175, 55)
    jurisdiction_text = (
        f"Declared State of Residence: {user_state}  |  "
        f"This report is informed by {user_state} estate planning statutes and probate rules."
    )
    pdf.multi_cell(0, 4.5, sanitize_for_pdf(jurisdiction_text), border=1, fill=True, align="C")
    pdf.ln(3)

    # Legal disclaimer
    pdf.set_fill_color(255, 248, 220)
    pdf.set_draw_color(212, 175, 55)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(80, 80, 80)
    disclaimer = (
        "IMPORTANT: This report is generated by an AI assistant for informational purposes only "
        "and does not constitute legal advice. For legally binding decisions, always consult a "
        "bar-certified attorney licensed in your jurisdiction."
    )
    pdf.multi_cell(0, 3.5, disclaimer, border=1, fill=True)
    pdf.ln(6)

    # Strip the boilerplate legal disclaimer from AI response
    content = data.content
    if "---\n*This analysis" in content:
        content = content[: content.index("---\n*This analysis")].strip()

    # Also strip the JSON block if present
    if "```checklist_json" in content:
        content = content[: content.index("```checklist_json")].strip()

    # Render content line by line with section-aware styling
    left_margin = pdf.l_margin
    for line in content.split("\n"):
        clean = sanitize_for_pdf(line.strip())
        if not clean:
            pdf.ln(2)
            continue

        pdf.set_x(left_margin)

        # Detect section headers for special styling
        clean_lower = clean.lower()
        is_section1 = "immediate action checklist" in clean_lower and "beneficiar" in clean_lower
        is_section2 = "estate strengthening" in clean_lower or (
            "recommendation" in clean_lower and "benefactor" in clean_lower
        )

        if is_section1:
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 14)
            pdf.set_text_color(34, 201, 147)
            heading = clean.lstrip("#* ").rstrip("*")
            pdf.multi_cell(0, 7, heading)
            pdf.set_font("Helvetica", "I", 8)
            pdf.set_text_color(100, 100, 100)
            pdf.cell(0, 5, "Actions for your loved ones to execute after your passing.", new_x="LMARGIN", new_y="NEXT")
            pdf.set_draw_color(34, 201, 147)
            pdf.line(left_margin, pdf.get_y(), left_margin + 170, pdf.get_y())
            pdf.ln(3)
        elif is_section2:
            pdf.ln(4)
            pdf.set_draw_color(212, 175, 55)
            pdf.line(left_margin, pdf.get_y(), left_margin + 170, pdf.get_y())
            pdf.ln(4)
            pdf.set_font("Helvetica", "B", 14)
            pdf.set_text_color(59, 130, 246)
            heading = clean.lstrip("#* ").rstrip("*")
            pdf.multi_cell(0, 7, heading)
            pdf.set_font("Helvetica", "I", 8)
            pdf.set_text_color(100, 100, 100)
            pdf.cell(
                0,
                5,
                "Actions for YOU (the benefactor) to take now to improve your estate plan.",
                new_x="LMARGIN",
                new_y="NEXT",
            )
            pdf.set_draw_color(59, 130, 246)
            pdf.line(left_margin, pdf.get_y(), left_margin + 170, pdf.get_y())
            pdf.ln(3)
        elif clean.startswith("##") or clean.startswith("**"):
            heading = clean.lstrip("#* ").rstrip("*")
            if heading:
                pdf.set_font("Helvetica", "B", 11)
                pdf.set_text_color(30, 40, 70)
                pdf.multi_cell(0, 5.5, heading)
                pdf.set_draw_color(212, 175, 55)
                pdf.line(left_margin, pdf.get_y(), left_margin + 170, pdf.get_y())
                pdf.ln(2)
        elif clean.startswith(("- ", "* ", "- [ ]", "- [x]")):
            bullet_text = clean.lstrip("-*[] x").strip()
            if bullet_text:
                check = "[x]" if "[x]" in clean else "[ ]" if "[ ]" in clean else "-"
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(40, 40, 40)
                pdf.cell(8, 5, check, new_x="RIGHT", new_y="TOP")
                pdf.multi_cell(0, 5, bullet_text)
        elif clean[0].isdigit() and "." in clean[:4]:
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(40, 40, 40)
            pdf.multi_cell(0, 5, clean)
        else:
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(60, 60, 60)
            pdf.multi_cell(0, 4.5, clean)

    # Footer
    pdf.ln(6)
    pdf.set_draw_color(200, 200, 200)
    pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 170, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(
        0,
        5,
        "AES-256-GCM Encrypted  |  Zero-Knowledge Architecture  |  2FA Protected",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.cell(
        0,
        5,
        f"CarryOn Technologies  |  carryon.us  |  {datetime.now(timezone.utc).year}",
        new_x="LMARGIN",
        new_y="NEXT",
    )

    pdf_bytes = bytes(pdf.output())
    if estate_id:
        await audit_log(
            action="guardian.iac_report_export",
            user_id=current_user["id"],
            resource_type="iac_report_pdf",
            estate_id=estate_id,
            details={"content_length": len(data.content)},
        )

    return Response(
        content=bytes(pdf_bytes),
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="CarryOn_IAC_Report_{datetime.now(timezone.utc).strftime("%Y%m%d")}.pdf"'
        },
    )


@router.post("/guardian/export-conversation")
async def export_conversation_pdf(
    data: dict,
    current_user: dict = Depends(get_current_user),
):
    """Generate a PDF of a complete EGA conversation."""
    from services.pdf_trust_footer import CarryOnPDF

    session_id = data.get("session_id")
    if not session_id:
        raise HTTPException(status_code=400, detail="session_id is required")

    # Fetch the conversation history
    history = (
        await db.chat_history.find(
            {"session_id": session_id, "user_id": current_user["id"]},
            {"_id": 0, "id": 1, "role": 1, "content": 1, "created_at": 1},
        )
        .sort("created_at", 1)
        .to_list(200)
    )
    if not history:
        raise HTTPException(status_code=404, detail="No conversation found")

    # Get estate context
    estates = await _get_user_estate(current_user, {"_id": 0, "id": 1, "name": 1})
    estate_name = estates[0]["name"] if estates else "My Estate"
    estate_id = estates[0]["id"] if estates else None
    user_name = current_user.get("name", "Benefactor")

    pdf = CarryOnPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Header
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(212, 175, 55)
    pdf.cell(0, 10, "Estate Guardian AI", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 5, sanitize_for_pdf(f"Conversation Transcript  |  {estate_name}"), new_x="LMARGIN", new_y="NEXT")
    pdf.cell(
        0,
        5,
        f"Exported: {datetime.now(timezone.utc).strftime('%B %d, %Y at %I:%M %p UTC')}",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.ln(3)

    # Disclaimer
    pdf.set_fill_color(255, 248, 220)
    pdf.set_draw_color(212, 175, 55)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(80, 80, 80)
    disclaimer = (
        "IMPORTANT: This transcript is generated by an AI assistant for informational purposes only "
        "and does not constitute legal advice. For legally binding decisions, always consult a "
        "bar-certified attorney licensed in your jurisdiction."
    )
    pdf.multi_cell(0, 3.5, disclaimer, border=1, fill=True)
    pdf.ln(6)

    left_margin = pdf.l_margin

    # Render messages
    for msg in history:
        role = msg.get("role", "user")
        content = msg.get("content", "")
        created_at = msg.get("created_at", "")

        # Strip the boilerplate legal disclaimer appended to AI responses
        if "---\n*This analysis" in content:
            content = content[: content.index("---\n*This analysis")].strip()

        # Role label
        pdf.set_x(left_margin)
        if role == "user":
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(59, 130, 246)
            pdf.cell(0, 6, sanitize_for_pdf(user_name), new_x="LMARGIN", new_y="NEXT")
        else:
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(34, 201, 147)
            pdf.cell(0, 6, "Estate Guardian", new_x="LMARGIN", new_y="NEXT")

        # Timestamp
        if created_at:
            try:
                from datetime import datetime as dt_cls

                ts = dt_cls.fromisoformat(created_at.replace("Z", "+00:00"))
                pdf.set_font("Helvetica", "", 7)
                pdf.set_text_color(150, 150, 150)
                pdf.cell(0, 4, ts.strftime("%b %d, %Y %I:%M %p"), new_x="LMARGIN", new_y="NEXT")
            except Exception:
                pass

        # Content — render line by line with basic markdown
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(40, 40, 40)
        for line in content.split("\n"):
            clean = sanitize_for_pdf(line.strip())
            if not clean:
                pdf.ln(2)
                continue
            pdf.set_x(left_margin)
            if clean.startswith("##") or clean.startswith("**"):
                heading = clean.lstrip("#* ").rstrip("*")
                if heading:
                    pdf.set_font("Helvetica", "B", 10)
                    pdf.set_text_color(30, 40, 70)
                    pdf.multi_cell(0, 5, heading)
                    pdf.set_font("Helvetica", "", 9)
                    pdf.set_text_color(40, 40, 40)
            elif clean.startswith(("- ", "* ")):
                pdf.cell(6, 5, "-", new_x="RIGHT", new_y="TOP")
                pdf.multi_cell(0, 5, clean.lstrip("-* ").strip())
            elif clean[0].isdigit() and "." in clean[:4]:
                pdf.multi_cell(0, 5, clean)
            else:
                pdf.multi_cell(0, 4.5, clean)

        # Separator
        pdf.ln(3)
        pdf.set_draw_color(220, 220, 220)
        pdf.line(left_margin, pdf.get_y(), left_margin + 170, pdf.get_y())
        pdf.ln(3)

    # Footer
    pdf.ln(4)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(
        0,
        5,
        "AES-256-GCM Encrypted  |  Zero-Knowledge Architecture  |  2FA Protected",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.cell(0, 5, "carryon.us  |  CarryOn Technologies", new_x="LMARGIN", new_y="NEXT")

    pdf_bytes = bytes(pdf.output())
    if estate_id:
        await audit_log(
            action="guardian.conversation_export",
            user_id=current_user["id"],
            resource_type="conversation_pdf",
            estate_id=estate_id,
            details={"session_id": session_id, "message_count": len(history)},
        )

    return Response(
        content=bytes(pdf_bytes),
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="CarryOn_EGA_Conversation_{datetime.now(timezone.utc).strftime("%Y%m%d")}.pdf"'
        },
    )


@router.post("/guardian/export-plan-of-action")
async def export_plan_of_action_pdf(
    data: dict,
    current_user: dict = Depends(get_current_user),
):
    """AI-summarize a chat session into a structured Plan of Action PDF."""
    from services.pdf_trust_footer import CarryOnPDF

    session_id = data.get("session_id")
    if not session_id:
        raise HTTPException(status_code=400, detail="session_id is required")

    # Fetch conversation
    history = (
        await db.chat_history.find(
            {"session_id": session_id, "user_id": current_user["id"]},
            {"_id": 0, "id": 1, "role": 1, "content": 1},
        )
        .sort("created_at", 1)
        .to_list(200)
    )
    if not history:
        raise HTTPException(status_code=404, detail="No conversation found")

    # Estate context
    estates = await _get_user_estate(current_user, {"_id": 0, "id": 1, "name": 1})
    estate_name = estates[0]["name"] if estates else "My Estate"
    estate_id = estates[0]["id"] if estates else None

    benefactor = await db.users.find_one({"id": current_user["id"]}, {"_id": 0, "id": 1, "name": 1, "address_state": 1})
    user_name = (benefactor or {}).get("name", "Benefactor")
    user_state = (benefactor or {}).get("address_state") or "Not specified"

    # Build conversation text for the AI summarizer
    conv_text = "\n".join(f"{'USER' if m['role'] == 'user' else 'GUARDIAN'}: {m['content']}" for m in history)

    # Ask the AI to produce a structured Plan of Action
    summary_prompt = f"""You are an estate planning expert. Below is a conversation between a benefactor and their Estate Guardian AI.

Analyze the entire conversation and produce a structured **Plan of Action** that summarizes:

1. **Key Topics Discussed** — What estate planning subjects were covered?
2. **Current Status** — What is already in place based on the discussion?
3. **Recommended Actions** — Specific, prioritized steps the benefactor should take, each with a clear description and urgency level (Immediate / Short-term / Long-term).
4. **State-Specific Considerations** — Any items specific to {user_state} law.
5. **Documents Needed** — Any legal documents that should be created, updated, or reviewed.
6. **Professional Consultations — Action Items by Professional**

Instead of a single referral list, break out the action items by the SPECIFIC professional the benefactor should consult, so they can hand each block to the right person. Use these sub-sections (omit any that have no action items — DO NOT include empty sub-sections):

   **6a. Estate Planning Attorney**
   List specific, numbered questions / asks for an attorney (e.g., draft / update will, create revocable trust, review beneficiary designations, durable power of attorney, healthcare directive, draft pour-over will, advance healthcare directive, HIPAA release, guardianship clauses for minors, state-specific probate planning).

   **6b. Tax / CPA**
   Tax-impacting items (e.g., estate-tax exposure analysis, gift-tax planning, step-up basis review, IRA/401(k) tax-deferred withdrawal strategy, charitable giving structures, state inheritance tax for {user_state}).

   **6c. Financial Advisor / Wealth Manager**
   Investment-related items (e.g., asset allocation in retirement, rebalancing, beneficiary designations on brokerage / IRA accounts, 529 plan setup, college funding, Roth conversion ladder).

   **6d. Life Insurance Agent**
   Coverage analysis (e.g., term vs. permanent review, beneficiary update, ILIT funding, key-person coverage, coverage gap analysis based on liabilities + dependents).

   **6e. Estate / Trust Administrator (Trustee / Executor)**
   Operational continuity items (e.g., confirm named executor is willing & able, name successor trustees, prepare letter of instruction, document asset locations, key custodians list, digital-asset access plan, funeral / disposition wishes).

   **6f. Other Specialists**
   Any other recommended consultations not covered above (e.g., elder-law attorney for Medicaid planning, special-needs trust attorney, business succession advisor, real-estate attorney for property transfers).

Format each section with clear markdown headers (## for top-level sections, ### for sub-sections like 6a/6b/6c…). Use numbered lists within each professional sub-section. Be specific and actionable — this will be printed as a formal Plan of Action document that the benefactor can literally hand to each professional.

CONVERSATION:
{conv_text}"""

    try:
        import time as _time2

        _t0 = _time2.time()
        completion = await asyncio.to_thread(
            xai_client.chat.completions.create,
            model=XAI_MODEL,
            messages=[{"role": "user", "content": summary_prompt}],
            temperature=0.4,
            max_tokens=4096,
        )
        plan_content = completion.choices[0].message.content
        try:
            from services.llm_cost_ledger import record_xai_response as _rec

            await _rec(
                completion,
                endpoint="guardian_exports.plan_of_action",
                model=XAI_MODEL,
                user_id=current_user.get("id"),
                estate_id=estate_id,
                started_at=_t0,
            )
        except Exception:
            pass
    except Exception as e:
        logger.error(f"Plan of Action generation failed: {e}")
        raise HTTPException(status_code=502, detail="Failed to generate Plan of Action")

    # Generate PDF
    pdf = CarryOnPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Header
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(212, 175, 55)
    pdf.cell(0, 10, "Estate Guardian AI", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(30, 40, 70)
    pdf.cell(0, 7, "Plan of Action", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(
        0,
        5,
        sanitize_for_pdf(f"Prepared for: {user_name}  |  Estate: {estate_name}  |  State: {user_state}"),
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.cell(
        0,
        5,
        f"Generated: {datetime.now(timezone.utc).strftime('%B %d, %Y at %I:%M %p UTC')}",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.ln(3)

    # Disclaimer
    pdf.set_fill_color(255, 248, 220)
    pdf.set_draw_color(212, 175, 55)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(80, 80, 80)
    disclaimer = (
        "IMPORTANT: This Plan of Action is generated by an AI assistant for informational purposes only "
        "and does not constitute legal advice. For legally binding decisions, always consult a "
        "bar-certified attorney licensed in your jurisdiction."
    )
    pdf.multi_cell(0, 3.5, disclaimer, border=1, fill=True)
    pdf.ln(6)

    # Render plan content
    left_margin = pdf.l_margin
    for line in plan_content.split("\n"):
        clean = sanitize_for_pdf(line.strip())
        if not clean:
            pdf.ln(2)
            continue
        pdf.set_x(left_margin)
        if clean.startswith("##") or clean.startswith("**"):
            heading = clean.lstrip("#* ").rstrip("*")
            if heading:
                pdf.set_font("Helvetica", "B", 11)
                pdf.set_text_color(30, 40, 70)
                pdf.multi_cell(0, 5.5, heading)
                pdf.set_draw_color(212, 175, 55)
                pdf.line(left_margin, pdf.get_y(), left_margin + 170, pdf.get_y())
                pdf.ln(2)
        elif clean.startswith(("- ", "* ")):
            bullet_text = clean.lstrip("-* ").strip()
            if bullet_text:
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(40, 40, 40)
                pdf.cell(6, 5, "-", new_x="RIGHT", new_y="TOP")
                pdf.multi_cell(0, 5, bullet_text)
        elif clean[0].isdigit() and "." in clean[:4]:
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(40, 40, 40)
            pdf.multi_cell(0, 5, clean)
        else:
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(60, 60, 60)
            pdf.multi_cell(0, 4.5, clean)

    # Footer
    pdf.ln(6)
    pdf.set_draw_color(200, 200, 200)
    pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 170, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(
        0,
        5,
        "AES-256-GCM Encrypted  |  Zero-Knowledge Architecture  |  2FA Protected",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.cell(0, 5, "carryon.us  |  CarryOn Technologies", new_x="LMARGIN", new_y="NEXT")

    pdf_bytes = bytes(pdf.output())
    if estate_id:
        await audit_log(
            action="guardian.plan_of_action_export",
            user_id=current_user["id"],
            resource_type="plan_of_action_pdf",
            estate_id=estate_id,
            details={"session_id": session_id, "message_count": len(history)},
        )

    return Response(
        content=bytes(pdf_bytes),
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="CarryOn_Plan_of_Action_{datetime.now(timezone.utc).strftime("%Y%m%d")}.pdf"'
        },
    )


@router.post("/guardian/beneficiary-export-checklist")
async def beneficiary_export_checklist_pdf(
    current_user: dict = Depends(get_current_user),
):
    """Generate a PDF IAC checklist for a beneficiary (post-transition).

    Finds the estate where the current user is a listed beneficiary,
    then generates the same formatted checklist PDF.
    """
    from services.pdf_trust_footer import CarryOnPDF

    # Find estate(s) where this user is a beneficiary
    estate = await db.estates.find_one({"beneficiaries": current_user["id"]}, {"_id": 0})
    if not estate:
        raise HTTPException(status_code=404, detail="No estate found for this beneficiary")

    estate_id = estate["id"]

    # Get checklist items
    items = await db.checklists.find({"estate_id": estate_id}, {"_id": 0}).sort("order", 1).to_list(200)
    if not items:
        raise HTTPException(status_code=404, detail="No checklist items found")

    # Get readiness data
    from services.readiness import calculate_estate_readiness

    readiness = await calculate_estate_readiness(estate_id)

    # Get benefactor info
    benefactor = await db.users.find_one(
        {"id": estate.get("owner_id")},
        {"_id": 0, "id": 1, "name": 1, "address_state": 1},
    )
    user_state = (benefactor or {}).get("address_state") or estate.get("state") or "Not specified"
    benefactor_name = (benefactor or {}).get("name", "Benefactor")

    # Build PDF (same format as benefactor checklist)
    pdf = CarryOnPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(212, 175, 55)
    pdf.cell(0, 12, "CarryOn Estate Guardian", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 6, f"Estate: {estate.get('name', 'My Estate')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Prepared by: {benefactor_name}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"State: {user_state}", new_x="LMARGIN", new_y="NEXT")
    score = readiness.get("overall_score", 0) if readiness else 0
    pdf.cell(0, 6, f"Readiness Score: {score}%", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(
        0,
        6,
        f"Generated: {datetime.now(timezone.utc).strftime('%B %d, %Y')}",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.ln(4)

    # Disclaimer
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(100, 100, 100)
    pdf.set_fill_color(245, 245, 245)
    disclaimer = (
        "IMPORTANT: This checklist is generated by an AI assistant for informational purposes only and does not constitute legal advice. "
        "CarryOn Estate Guardian is not a licensed attorney. For legally binding decisions, always consult a bar-certified "
        "attorney licensed in your jurisdiction."
    )
    pdf.multi_cell(0, 3.5, disclaimer, border=1, fill=True)
    pdf.ln(6)

    # Only show beneficiary action items (not benefactor recommendations)
    beneficiary_items = [i for i in items if i.get("section") != "benefactor_recommendation"]

    category_labels = {
        "immediate": "Immediate (Days 1-3)",
        "first_week": "First Week",
        "two_weeks": "Within Two Weeks",
        "first_month": "First Month",
        "legal": "Legal",
        "financial": "Financial",
        "insurance": "Insurance",
        "property": "Property",
        "medical": "Medical",
        "personal": "Personal",
        "government": "Government",
        "general": "General",
    }

    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(34, 201, 147)
    pdf.cell(0, 9, "Action Checklist for Beneficiaries", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    if beneficiary_items:
        cats: dict[str, list] = {}
        for item in beneficiary_items:
            cat = item.get("category", item.get("due_timeframe", "general"))
            if cat not in cats:
                cats[cat] = []
            cats[cat].append(item)

        for cat, cat_items in cats.items():
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(30, 40, 70)
            pdf.cell(0, 7, category_labels.get(cat, cat.replace("_", " ").title()), new_x="LMARGIN", new_y="NEXT")
            pdf.ln(1)
            for item in cat_items:
                check = "[X]" if item.get("is_completed") else "[ ]"
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(50, 50, 50)
                title = item.get("title", "Untitled")
                pdf.cell(0, 5, f"  {check}  {sanitize_for_pdf(title)}", new_x="LMARGIN", new_y="NEXT")
                if item.get("description"):
                    pdf.set_x(pdf.get_x() + 8)
                    pdf.set_font("Helvetica", "", 8)
                    pdf.set_text_color(100, 100, 100)
                    pdf.multi_cell(162, 4, sanitize_for_pdf(item["description"][:200]))
                pdf.ln(2)
    else:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(120, 120, 120)
        pdf.cell(0, 6, "No action items found.", new_x="LMARGIN", new_y="NEXT")

    # Footer
    pdf.ln(6)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(
        0, 5, "AES-256-GCM Encrypted  |  Zero-Knowledge Architecture  |  2FA Protected", new_x="LMARGIN", new_y="NEXT"
    )
    pdf.cell(
        0,
        5,
        f"CarryOn Technologies  |  carryon.us  |  {datetime.now(timezone.utc).year}",
        new_x="LMARGIN",
        new_y="NEXT",
    )

    pdf_bytes = bytes(pdf.output())
    return Response(
        content=bytes(pdf_bytes),
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="CarryOn_IAC_{datetime.now(timezone.utc).strftime("%Y%m%d")}.pdf"'
        },
    )
