"""CarryOn™ — Public PDF verification endpoint.

Serves the snapshot referenced by a QR code stamped on a CarryOn
PDF, alongside the canonical Prime Directive payload. A professional
reviewing a user's PDF scans the QR, lands here, and confirms in
<5 seconds that:

  • the document was generated by CarryOn (HMAC verified);
  • the inputs printed in the Verified Inputs Manifest match what
    CarryOn has on file as of the PDF's generation date; and
  • the locked Prime Directive in force at that moment is the
    contract still in force today (or has changed — the lock date is
    surfaced for both).

The endpoint is GET-only, no auth, no PII beyond what the PDF reader
already has in hand. Safe to share.
"""

from fastapi import APIRouter

from services.pdf_verification import read_snapshot
from services.prime_directive import prime_directive_payload

router = APIRouter()


@router.get("/verify/{verify_token}")
async def get_pdf_verification(verify_token: str):
    """Resolve a CarryOn PDF QR token to its verification payload.

    Always returns 200 — the ``verified`` boolean tells the frontend
    whether to render the success or failure path. Returning a
    structured failure (instead of 404) preserves the contract that
    professionals reading the QR always land on a usable page.
    """
    snapshot = await read_snapshot(verify_token)
    if snapshot is None:
        return {
            "verified": False,
            "reason": (
                "We could not verify this CarryOn document. The QR code may "
                "have been altered, the snapshot may have been deleted, or "
                "the document may not have been generated by CarryOn. "
                "If you believe this is in error, contact the person who "
                "shared the document with you."
            ),
            "prime_directive": prime_directive_payload(),
        }

    return {
        "verified": True,
        "snapshot": snapshot,
        "prime_directive": prime_directive_payload(),
    }
