"""Auto-classified bulk route policy import (Feb 12, 2026).

563 routes classified by heuristic — every entry carries the note
"auto-classified — review" and should be hand-audited in the post-pitch
sweep. New routes added after this date should NOT land here; they
should be hand-classified in route_policies.py.

To regenerate: re-run scripts/check_route_policies.py with the bulk
classifier (see commit history Feb 12, 2026).
"""

# Auto-classified bulk import Feb 12, 2026 — REVIEW THESE NOTES IN POST-PITCH SWEEP
AUTO_IMPORTED_POLICIES = {
    "DELETE /api/admin/announcements/{announcement_id}": {
        "auth": "required",
        "roles": ["admin"],
        "notes": "auto-classified \u2014 review",
    },
    "DELETE /api/admin/b2b-codes/{code_id}": {
        "auth": "required",
        "roles": ["admin"],
        "notes": "auto-classified \u2014 review",
    },
    "DELETE /api/admin/estates/{estate_id}": {
        "auth": "required",
        "roles": ["admin"],
        "notes": "auto-classified \u2014 review",
    },
    "DELETE /api/admin/founders-circle/subscriptions/pending": {
        "auth": "required",
        "roles": ["admin"],
        "notes": "auto-classified \u2014 review",
    },
    "DELETE /api/admin/knowledge-base/{article_id}": {
        "auth": "required",
        "roles": ["admin"],
        "notes": "auto-classified \u2014 review",
    },
    "DELETE /api/admin/notification-categories/{category_id}": {
        "auth": "required",
        "roles": ["admin"],
        "notes": "auto-classified \u2014 review",
    },
    "DELETE /api/admin/partners/{partner_id}": {
        "auth": "required",
        "roles": ["admin"],
        "notes": "auto-classified \u2014 review",
    },
    "DELETE /api/admin/scoped-admins/{admin_id}": {
        "auth": "required",
        "roles": ["admin"],
        "notes": "auto-classified \u2014 review",
    },
    "DELETE /api/admin/support/conversation/{conversation_id}": {
        "auth": "required",
        "roles": ["admin"],
        "notes": "auto-classified \u2014 review",
    },
    "DELETE /api/admin/users/{user_id}": {
        "auth": "required",
        "roles": ["admin"],
        "notes": "auto-classified \u2014 review",
    },
    "DELETE /api/admin/verifications/{verification_id}": {
        "auth": "required",
        "roles": ["admin"],
        "notes": "auto-classified \u2014 review",
    },
    "DELETE /api/admin/voices/{submission_id}": {
        "auth": "required",
        "roles": ["admin"],
        "notes": "auto-classified \u2014 review",
    },
    "DELETE /api/auth/passkeys/{passkey_id}": {"auth": "required", "roles": "self"},
    "DELETE /api/auth/sms-otp": {"auth": "required", "roles": "self"},
    "DELETE /api/beneficiary/concierge/session/{session_id}": {
        "auth": "required",
        "notes": "auto-classified \u2014 review",
    },
    "DELETE /api/ccp/plans/{plan_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "DELETE /api/ccp/plans/{plan_id}/share": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "DELETE /api/chat/sessions": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "DELETE /api/chat/sessions/{session_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "DELETE /api/digital-wallet/{entry_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "DELETE /api/documents/{document_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "DELETE /api/dts/tasks/{task_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "DELETE /api/estate-chat/channels/{channel_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "DELETE /api/estate-chat/messages/{message_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "DELETE /api/estates/{estate_id}": {
        "auth": "required",
        "estate_access": "owner",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "DELETE /api/family-plan/{plan_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "DELETE /api/family-plan/{plan_id}/member/{user_id}": {
        "auth": "required",
        "notes": "auto-classified \u2014 review",
    },
    "DELETE /api/ffn/{contact_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "DELETE /api/financial/accounts/{account_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "DELETE /api/financial/beneficiary-blocks/{block_id}": {
        "auth": "required",
        "notes": "auto-classified \u2014 review",
    },
    "DELETE /api/financial/bills/{bill_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "DELETE /api/financial/categories/{category_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "DELETE /api/financial/debts/{debt_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "DELETE /api/financial/entities/{entity_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "DELETE /api/financial/entity-relationships/{rel_id}": {
        "auth": "required",
        "notes": "auto-classified \u2014 review",
    },
    "DELETE /api/financial/external-people/{person_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "DELETE /api/financial/payments/{payment_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "DELETE /api/financial/property/{property_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "DELETE /api/founder/invites/{token}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "DELETE /api/founder/invites/{token}/permanent": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "DELETE /api/founder/operators/{operator_id}": {"auth": "required", "roles": ["admin", "operator"]},
    "DELETE /api/founder/requests/{request_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "DELETE /api/ops/canned-responses/{response_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "DELETE /api/ops/shifts/{shift_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "DELETE /api/ops/training/complete/{module_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "DELETE /api/pdfs/latest/{pdf_type}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "DELETE /api/push/unsubscribe": {"auth": "required", "roles": "self"},
    "DELETE /api/security/settings/{section_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "DELETE /api/transition/certificates/{certificate_id}": {
        "auth": "required",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/activity/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/activity": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/analytics-digest/preview": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/announcements": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/audit-digest/preview": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/b2b-codes": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/beta-tickets": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/beta-users": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/code-health": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/deletion-requests": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/dev-switcher": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/download-diagnostics": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/email-preferences": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/emergency-access": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/estate-diagnostic": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/estate-health": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/export/subscriptions": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/export/users": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/family-plans": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/feature-gates": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/founders-circle/subscriptions": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/funnel-analytics": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/funnel/analytics": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/grace-periods": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/integrations": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/ip-whitelist": {"auth": "required", "roles": ["admin"], "notes": "auto-classified \u2014 review"},
    "GET /api/admin/knowledge-base": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/launch-metrics": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/launch-war-room": {
        "auth": "required",
        "roles": ["admin"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/maintenance-mode": {
        "auth": "required",
        "roles": ["admin"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/maintenance/reprocess-avatars/scan": {
        "auth": "required",
        "roles": ["admin"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/notification-categories": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/partners": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/platform-rules": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/platform-settings": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/referrals": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/revenue-metrics": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/scoped-admins": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/security-scan": {"auth": "required", "roles": ["admin"], "notes": "auto-classified \u2014 review"},
    "GET /api/admin/session-policy": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/stats": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/subscription-stats": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/system-health": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/trial-policy": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/trial-users": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/user/{user_id}/master-key-hint": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/verifications": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/verifications/{verification_id}/document": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/voices": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/voices/export": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/voices/pending-count": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/admin/xai-credits": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/auth/2fa-preference": {"auth": "required", "roles": "self"},
    "GET /api/auth/offline/status": {"auth": "required", "roles": "self"},
    "GET /api/auth/passkeys": {"auth": "required", "roles": "self"},
    "GET /api/auth/profile": {"auth": "required", "roles": "self"},
    "GET /api/auth/sms-otp-status": {"auth": "required", "roles": "self"},
    "GET /api/auth/username": {"auth": "required", "roles": "self"},
    "GET /api/beneficiaries/access-requests/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/beneficiaries/{estate_id}/primary": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/beneficiaries/{estate_id}/succession": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/beneficiary/concierge/diagnose": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/beneficiary/concierge/document/{doc_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/beneficiary/concierge/history": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/beneficiary/concierge/sessions": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/beneficiary/concierge/status": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/beneficiary/essential-docs/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/beneficiary/family-connections": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/beneficiary/my-permissions/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/beneficiary/my-primary-for": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/ccp/activation/{activation_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/ccp/activations/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/ccp/active/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/ccp/active/{estate_id}/linked-resources": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/ccp/debrief-stats/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/ccp/drill/history/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/ccp/go-bag/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/ccp/history/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/ccp/household/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/ccp/members/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/ccp/my-plans": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/ccp/out-of-area/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/ccp/plans/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/ccp/readiness/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/ccp/rendezvous/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/changelog/since": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/chat/history/{session_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/chat/sessions": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/compliance/consent": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/compliance/data-export": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/compliance/incidents": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/compliance/retention-policy": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/compliance/sensitive-access-log": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/dev-switcher/config": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/digest/preferences": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/digital-wallet/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/documents/{document_id}/download": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/documents/{document_id}/preview": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/documents/{estate_id}/essential-slots": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/documents/{estate_id}/pre-transition": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/downloads/ffmpeg-check": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/downloads/{token}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/dts/task/{task_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/dts/tasks/all": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/dts/tasks/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/emergency-access/active": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/emergency-access/my-requests": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/estate-chat/channels": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/estate-chat/channels/{channel_id}/messages": {
        "auth": "required",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/estate-chat/channels/{channel_id}/pinned": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/estate-chat/channels/{channel_id}/read-status": {
        "auth": "required",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/estate-chat/channels/{channel_id}/typing": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/estate-chat/contacts": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/estate-chat/files/{file_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/estate-chat/search": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/estate-chat/unread-total": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/estate/{estate_id}/export-pdf": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/estate/{estate_id}/readiness": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/estate/{estate_id}/section-permissions": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/estates/rename-check": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/family-plan/eligible-beneficiaries": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/family-plan/preview-savings": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/family-plan/status": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/ffn/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/financial/accounts/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/financial/beneficiary-blocks/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/financial/bills/{bill_id}/payments": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/financial/bills/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/financial/cashflow/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/financial/categories/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/financial/debts/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/financial/entities-share/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/financial/entities/beneficiary-view/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/financial/entities/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/financial/handoff-package/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/financial/health-score/{estate_id}": {"auth": "public"},
    "GET /api/financial/portal/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/financial/property/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/financial/summary/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/founder-about/verify/{token}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/founder/audit-trail": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/founder/audit-trail/export": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/founder/invites": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/founder/operators": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/founder/p1-contact-settings": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/founder/p1-contact-settings-public": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/founder/requests": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/founders-circle/checkout-status/{session_id}": {
        "auth": "required",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/founders-circle/plans": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/founders-circle/status": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/guardian/iac-task-status": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/guardian/usage/today": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/image/{card_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/invitations/{token}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/messages/video-dl/{video_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/messages/video/{video_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/messages/voice/{voice_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/milestones/deliveries": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/milestones/deliveries/stats": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/milestones/deliveries/{delivery_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/notification-prefs": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/notifications": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/notifications/unread-count": {"auth": "required", "roles": "self"},
    "GET /api/onboarding/progress": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/onboarding/status": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/ops/canned-responses": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/ops/customer-context/{user_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/ops/dashboard": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/ops/dashboard-events": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/ops/escalations": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/ops/my-activity": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/ops/performance": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/ops/search": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/ops/shift-notes": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/ops/shifts": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/ops/shifts/summary": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/ops/shifts/swap-requests": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/ops/sla-config": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/ops/team-tasks": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/ops/training/modules": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/ops/training/team-progress": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/partner-brief": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/partners/lookup/{code}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/pdfs/latest": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/pdfs/latest/{pdf_type}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/photos/{key:path}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/public/ccp/{share_token}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/public/maintenance-status": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/public/partners/{slug}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/public/partners/{slug}/logo": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/public/site-content": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/push/vapid-public-key": {"auth": "required", "roles": "self"},
    "GET /api/referrals/me": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/security/master-key-status": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/security/questions": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/security/settings": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/security/unlock-status/{section_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/status": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/subscriptions/beneficiary/lifecycle-status": {
        "auth": "required",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/subscriptions/checkout-status/{session_id}": {
        "auth": "required",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/subscriptions/enabled-features": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/support/conversations": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/support/conversations-by-thread": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/support/messages": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/support/messages/{conversation_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/support/threads": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/support/unread-count": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/team/channels": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/team/messages/{channel_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/team/staff": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/templates/scenarios": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/timeline/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/transition/certificate/{cert_id}/document": {
        "auth": "required",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/transition/certificates": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/transition/certificates/all": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/transition/status/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/user-preferences/chat-autoscroll": {"auth": "required", "roles": "self"},
    "GET /api/user-preferences/dock": {"auth": "required", "roles": "self"},
    "GET /api/user-preferences/menu-order": {"auth": "required", "roles": "self"},
    "GET /api/user-preferences/onboarding-emails": {"auth": "required", "roles": "self"},
    "GET /api/user-preferences/scroll-restoration": {"auth": "required", "roles": "self"},
    "GET /api/vault/security-info/{estate_id}": {
        "auth": "required",
        "estate_access": "member",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "GET /api/verification/status": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/voices/moderate": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/voices/public": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "GET /api/{upload_id}/status": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PATCH /api/admin/voices/{submission_id}/approve": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "PATCH /api/admin/voices/{submission_id}/feature": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "PATCH /api/admin/voices/{submission_id}/reject": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "PATCH /api/ccp/plans/{plan_id}/drill-schedule": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PATCH /api/estates/{estate_id}": {
        "auth": "required",
        "estate_access": "owner",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "PATCH /api/financial/beneficiary-blocks/{block_id}": {
        "auth": "required",
        "notes": "auto-classified \u2014 review",
    },
    "PATCH /api/financial/entities-share/{estate_id}": {
        "auth": "required",
        "estate_access": "owner",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "PATCH /api/financial/entities/{entity_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PATCH /api/financial/entity-relationships/{rel_id}": {
        "auth": "required",
        "notes": "auto-classified \u2014 review",
    },
    "PATCH /api/financial/external-people/{person_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/accounts/add-beneficiary-link": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/accounts/create-estate": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/admin/analytics-digest/send": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/audit-digest/send": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/b2b-codes": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/beneficiary/trigger-transition": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/bulk/assign-tier": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/bulk/toggle-beta": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/cleanup-ghost-estates": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/cleanup-orphans": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/emergency-access/{request_id}/review": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/grace-periods/{gp_id}/confirm": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/grace-periods/{gp_id}/hold": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/grace-periods/{gp_id}/purge": {
        "auth": "required",
        "roles": ["admin"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/grace-periods/{gp_id}/purge-mm": {
        "auth": "required",
        "roles": ["admin"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/integrations/soc2-report": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/integrations/unlock": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/knowledge-base": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/maintenance/reprocess-avatars": {
        "auth": "required",
        "roles": ["admin"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/migrate-photos": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/notification-categories": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/partners": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/partners/{partner_id}/logo": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/partners/{partner_id}/send-welcome": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/platform-rules/generate-narrative": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/platform-rules/generate-narratives": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/scoped-admins": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/support/conversation/{conversation_id}/restore": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/trial-reminders/send": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/user/{user_id}/unlock-all-documents": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/user/{user_id}/verify-master-key": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/users/{user_id}/reset-trial": {
        "auth": "required",
        "roles": ["admin"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/verifications/{verification_id}/notify": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/verifications/{verification_id}/restore": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/verifications/{verification_id}/review": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/voices/digest/send-now": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/voices/seed": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/voices/social-brief/send-now": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/admin/xai-credits/set-balance": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/auth/check-email": {"auth": "required", "roles": "self"},
    "POST /api/auth/check-username": {"auth": "required", "roles": "self"},
    "POST /api/auth/dev-login": {"auth": "required", "roles": "self"},
    "POST /api/auth/dev-switch": {"auth": "required", "roles": "self"},
    "POST /api/auth/forgot-username": {"auth": "required", "roles": "self"},
    "POST /api/auth/notify-username-migration": {"auth": "required", "roles": "self"},
    "POST /api/auth/offline/enroll": {"auth": "required", "roles": "self"},
    "POST /api/auth/offline/revoke": {"auth": "required", "roles": "self"},
    "POST /api/auth/resend-otp": {"auth": "required", "roles": "self"},
    "POST /api/auth/sms-otp-setup": {"auth": "required", "roles": "self"},
    "POST /api/auth/sms-otp-verify": {"auth": "required", "roles": "self"},
    "POST /api/auth/verify-otp": {"auth": "public"},
    "POST /api/auth/verify-password": {"auth": "required", "roles": "self"},
    "POST /api/auth/webauthn/login": {"auth": "public"},
    "POST /api/auth/webauthn/login-options": {"auth": "public"},
    "POST /api/auth/webauthn/register": {"auth": "public"},
    "POST /api/auth/webauthn/register-options": {"auth": "public"},
    "POST /api/beneficiaries/force-link": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/beneficiaries/request-access": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/beneficiaries/{beneficiary_id}/invite": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/beneficiary/become-benefactor": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/beta/accept": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/beta/feedback": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/ccp/activate": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/ccp/activation/end/{activation_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/ccp/activation/start": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/ccp/activation/status": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/ccp/checkin": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/ccp/deactivate/{activation_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/ccp/debrief/{activation_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/ccp/drill/run": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/ccp/plans": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/ccp/plans/{plan_id}/share": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/ccp/risk-profile": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/ccp/wizard/generate": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/chat/guardian": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/compliance/deletion-request": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/compliance/incident": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/diagnostics/download-event": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/diagnostics/funnel-event": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/digest/preview": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/digest/preview-enhanced": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/digest/send-weekly": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/digital-wallet": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/documents/{document_id}/lock": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/documents/{document_id}/remove-lock": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/documents/{document_id}/unlock": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/downloads/prepare": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/dts/tasks": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/dts/tasks/{task_id}/approve-all": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/dts/tasks/{task_id}/approve-item": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/dts/tasks/{task_id}/assign": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/dts/tasks/{task_id}/payment-method": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/dts/tasks/{task_id}/quote": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/dts/tasks/{task_id}/restore": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/dts/tasks/{task_id}/status": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/emergency-access/request": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/errors/report": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/estate-chat/channels": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/estate-chat/channels/batch-delete": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/estate-chat/channels/{channel_id}/messages": {
        "auth": "required",
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/estate-chat/channels/{channel_id}/typing": {
        "auth": "required",
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/estate-chat/channels/{channel_id}/upload": {
        "auth": "required",
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/estate-chat/channels/{channel_id}/upload-multi": {
        "auth": "required",
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/estate-chat/messages/{message_id}/pin": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/estate-chat/messages/{message_id}/react": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/estate/{estate_id}/readiness": {
        "auth": "required",
        "estate_access": "owner",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/estates/customize-name": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/family-plan/create": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/family-plan/{plan_id}/add-member": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/ffn/{estate_id}": {
        "auth": "required",
        "estate_access": "owner",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/financial/accounts": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/financial/beneficiary-blocks": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/financial/bills": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/financial/bills/bulk-pay": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/financial/bills/{bill_id}/pay": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/financial/categories": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/financial/debts": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/financial/entities": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/financial/entity-relationships": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/financial/external-people": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/financial/external-people/{person_id}/photo": {
        "auth": "required",
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/financial/property": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/financial/smart-categorize": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/founder-about/login": {"auth": "public"},
    "POST /api/founder/invites": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/founder/invites/clear-revoked": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/founder/operator-dev-login": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/founder/operators": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/founder/requests": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/founder/requests/clear-inactive": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/founder/requests/{request_id}/approve": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/founder/requests/{request_id}/deny": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/founder/requests/{request_id}/revoke": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/founders-circle": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/founders-circle/checkout": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/funnel/complete": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/funnel/convert": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/funnel/start": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/funnel/step": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/guardian/beneficiary-export-checklist": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/guardian/export-checklist": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/guardian/export-conversation": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/guardian/export-plan-of-action": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/guardian/iac-task/cancel": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/init": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/invitations/accept": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/invitations/accept-existing": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/milestones/deliveries/{delivery_id}/review": {
        "auth": "required",
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/milestones/process-scheduled": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/milestones/report": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/notifications/read-all": {"auth": "required", "roles": "self"},
    "POST /api/notifications/{notification_id}/read": {"auth": "required", "roles": "self"},
    "POST /api/onboarding/celebration-shown": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/onboarding/complete-step/{step_key}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/onboarding/dismiss": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/onboarding/reset": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/ops/canned-responses": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/ops/canned-responses/{response_id}/use": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/ops/escalations": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/ops/shift-notes": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/ops/shift-notes/{note_id}/acknowledge": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/ops/shifts": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/ops/shifts/swap-requests": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/ops/tasks/assign": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/ops/tasks/claim": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/ops/tasks/unclaim": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/ops/training/complete": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/ops/training/modules": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/partner-brief/reset": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/partners/redeem-code": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/pdfs/cache": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/push/subscribe": {"auth": "required", "roles": "self"},
    "POST /api/referrals/claim": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/referrals/track-visit": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/security/master-key": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/security/verify-master-key": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/security/verify/{section_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/subscriber": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/subscriptions/family-plan-request": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/subscriptions/verify-b2b-code": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/support/messages": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/support/p1-emergency": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/support/threads": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/team/channels/direct": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/team/messages": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/templates/apply": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/transition/approve/{certificate_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/transition/begin-review/{certificate_id}": {
        "auth": "required",
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/transition/certificates/{certificate_id}/restore": {
        "auth": "required",
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/transition/certificates/{certificate_id}/soft-delete": {
        "auth": "required",
        "notes": "auto-classified \u2014 review",
    },
    "POST /api/transition/reject/{certificate_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/transition/upload-certificate": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/verification/upload": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/voice/transcribe": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/voice/verify-passphrase": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/warmup": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/webhook/apple": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "POST /api/{upload_id}/complete": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/admin/b2b-codes/{code_id}": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/admin/beta-tickets/{ticket_id}/status": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/admin/dev-switcher": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/admin/dev-switcher/portal-visibility": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/admin/email-preferences": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/admin/estate/{estate_id}/tier": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/admin/family-plan-settings": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/admin/feature-gates": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/admin/founders-circle/pricing": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/admin/integrations-pin": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/admin/integrations/{integration_id}": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/admin/ip-whitelist": {"auth": "required", "roles": ["admin"], "notes": "auto-classified \u2014 review"},
    "PUT /api/admin/knowledge-base/{article_id}": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/admin/maintenance-mode": {
        "auth": "required",
        "roles": ["admin"],
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/admin/notification-categories/{category_id}": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/admin/partners/{partner_id}": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/admin/platform-rules": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/admin/platform-rules/narrative": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/admin/platform-settings": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/admin/scoped-admins/{admin_id}": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/admin/session-policy": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/admin/trial-policy": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/admin/user/{user_id}/beta": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/admin/users/{user_id}/ai-unlimited": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/admin/users/{user_id}/role": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/admin/users/{user_id}/session-exempt": {
        "auth": "required",
        "roles": ["admin", "operator"],
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/auth/2fa-preference": {"auth": "required", "roles": "self"},
    "PUT /api/auth/display-name": {"auth": "required", "roles": "self"},
    "PUT /api/auth/profile": {"auth": "required", "roles": "self"},
    "PUT /api/auth/profile-photo": {"auth": "required", "roles": "self"},
    "PUT /api/auth/username": {"auth": "required", "roles": "self"},
    "PUT /api/beneficiaries/access-requests/{request_id}": {
        "auth": "required",
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/beneficiaries/reorder/{estate_id}": {
        "auth": "required",
        "estate_access": "owner",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/beneficiaries/{beneficiary_id}/set-primary": {
        "auth": "required",
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/beneficiaries/{beneficiary_id}/toggle-succession": {
        "auth": "required",
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/beneficiary/display-override": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/ccp/go-bag/{estate_id}": {
        "auth": "required",
        "estate_access": "owner",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/ccp/household/{estate_id}": {
        "auth": "required",
        "estate_access": "owner",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/ccp/out-of-area/{estate_id}": {
        "auth": "required",
        "estate_access": "owner",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/ccp/plans/{plan_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/ccp/rendezvous/{estate_id}": {
        "auth": "required",
        "estate_access": "owner",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/compliance/consent": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/digest/preferences": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/digital-wallet/{entry_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/documents/{document_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/documents/{document_id}/ai-eligible": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/documents/{document_id}/designate-beneficiaries": {
        "auth": "required",
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/documents/{document_id}/pin-offline": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/dts/tasks/{task_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/estate-chat/channels/{channel_id}/members": {
        "auth": "required",
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/estate-chat/messages/{message_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/estate/{estate_id}/section-permissions": {
        "auth": "required",
        "estate_access": "owner",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/estates/set-primary/{estate_id}": {
        "auth": "required",
        "estate_access": "owner",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/estates/{estate_id}/photo": {
        "auth": "required",
        "estate_access": "owner",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/family-plan/{plan_id}/successor": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/ffn/{contact_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/financial/accounts/{account_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/financial/bills/{bill_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/financial/debts/{debt_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/financial/entities/{estate_id}/layout": {
        "auth": "required",
        "estate_access": "owner",
        "estate_id_source": "path.estate_id",
        "notes": "auto-classified \u2014 review",
    },
    "PUT /api/financial/property/{property_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/financial/{module}/{item_id}/designation": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/founder/operators/{operator_id}": {"auth": "required", "roles": ["admin", "operator"]},
    "PUT /api/founder/p1-contact-settings": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/notification-prefs": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/ops/canned-responses/{response_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/ops/escalations/{escalation_id}/resolve": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/ops/escalations/{escalation_id}/veto": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/ops/shifts/swap-requests/{request_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/ops/shifts/{shift_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/ops/sla-config": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/ops/tasks/prioritize": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/partner-brief": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/security/settings/{section_id}": {"auth": "required", "notes": "auto-classified \u2014 review"},
    "PUT /api/user-preferences/chat-autoscroll": {"auth": "required", "roles": "self"},
    "PUT /api/user-preferences/dock": {"auth": "required", "roles": "self"},
    "PUT /api/user-preferences/menu-order": {"auth": "required", "roles": "self"},
    "PUT /api/user-preferences/onboarding-emails": {"auth": "required", "roles": "self"},
    "PUT /api/user-preferences/scroll-restoration": {"auth": "required", "roles": "self"},
    "PUT /api/{upload_id}/chunk": {"auth": "required", "notes": "auto-classified \u2014 review"},
}
