import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { ShieldCheck, ShieldOff, Lock, Loader2, ExternalLink } from 'lucide-react';
import { API_URL } from '../config';

/**
 * Public verification page for CarryOn-generated PDFs.
 *
 * A professional reviewing a user's PDF scans the QR code printed on
 * any page → lands here → sees (a) whether the document is
 * authentic (HMAC verified against the locked snapshot), (b) the
 * locked Prime Directive in force when the PDF was generated, and
 * (c) the exact user inputs the document was built on.
 *
 * The page is public, no auth, no telemetry, no PII the reader
 * does not already have in hand on the printed page.
 */
const VerifyPage = () => {
  const { hash } = useParams();
  const [payload, setPayload] = useState(null);
  const [loadError, setLoadError] = useState('');

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch(`${API_URL}/verify/${encodeURIComponent(hash)}`);
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const data = await res.json();
        if (!cancelled) setPayload(data);
      } catch (e) {
        if (!cancelled) setLoadError(e.message || 'Unable to load.');
      }
    })();
    return () => { cancelled = true; };
  }, [hash]);

  const baseShell = {
    minHeight: '100vh',
    background: '#FAF7F1',
    color: '#0F1629',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif',
    padding: '64px 24px 96px',
  };

  if (!payload && !loadError) {
    return (
      <div data-testid="verify-page" style={baseShell}>
        <div style={{ maxWidth: 720, margin: '0 auto', display: 'flex', alignItems: 'center', gap: 10, color: '#6B7280' }}>
          <Loader2 size={16} className="animate-spin" />
          Verifying document…
        </div>
      </div>
    );
  }

  if (loadError) {
    return (
      <div data-testid="verify-page" style={baseShell}>
        <div data-testid="verify-error" style={{ maxWidth: 720, margin: '0 auto', padding: 16, background: '#FEF2F2', border: '1px solid #FCA5A5', borderRadius: 8, color: '#991B1B', fontSize: 14 }}>
          We couldn't reach the verification service ({loadError}). Please try again in a moment.
        </div>
      </div>
    );
  }

  const verified = payload.verified;
  const snapshot = payload.snapshot;
  const directive = payload.prime_directive;

  return (
    <div data-testid="verify-page" style={baseShell}>
      <div style={{ maxWidth: 760, margin: '0 auto' }}>
        {/* Status badge */}
        <div
          data-testid={verified ? 'verify-status-success' : 'verify-status-failure'}
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: 10,
            padding: '8px 16px',
            background: verified ? '#ECFDF5' : '#FEF2F2',
            border: `1px solid ${verified ? '#10B981' : '#DC2626'}`,
            borderRadius: 999,
            fontSize: 13,
            letterSpacing: '0.04em',
            textTransform: 'uppercase',
            fontWeight: 700,
            color: verified ? '#047857' : '#991B1B',
            marginBottom: 24,
          }}
        >
          {verified ? <ShieldCheck size={14} strokeWidth={2.5} /> : <ShieldOff size={14} strokeWidth={2.5} />}
          {verified ? 'Document verified by CarryOn' : 'Verification failed'}
        </div>

        <h1 style={{ fontSize: 32, lineHeight: 1.2, fontWeight: 800, letterSpacing: '-0.02em', margin: '0 0 12px 0' }}>
          {verified ? 'Authentic CarryOn document' : 'We could not verify this document'}
        </h1>

        {!verified && (
          <p data-testid="verify-failure-reason" style={{ fontSize: 15, lineHeight: 1.6, color: '#3C4A5E', margin: '0 0 32px 0' }}>
            {payload.reason}
          </p>
        )}

        {verified && (
          <>
            <p style={{ fontSize: 15, lineHeight: 1.6, color: '#3C4A5E', margin: '0 0 32px 0' }}>
              This document was generated by CarryOn on{' '}
              <strong data-testid="verify-generated-at">{new Date(snapshot.generated_at).toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })}</strong>
              . The structured inputs the document was built on are listed below — exactly as the user provided them on that date.
            </p>

            {/* Verified Inputs Manifest */}
            <article
              data-testid="verify-manifest"
              style={{
                background: '#FFFFFF',
                border: '1px solid #E5DDC8',
                borderRadius: 12,
                padding: '32px 28px',
                boxShadow: '0 1px 2px rgba(15,22,41,0.04), 0 12px 32px rgba(15,22,41,0.06)',
                marginBottom: 32,
              }}
            >
              <h2 style={{ fontSize: 18, fontWeight: 700, margin: '0 0 18px 0' }}>Verified Inputs</h2>
              {(snapshot.manifest_entries || []).length === 0 && (
                <p style={{ fontSize: 14, color: '#6B7280' }}>This document does not carry a structured-input manifest.</p>
              )}
              {(snapshot.manifest_entries || []).map((entry, i) => (
                <div
                  key={i}
                  data-testid={`verify-manifest-entry-${i}`}
                  style={{
                    paddingBottom: 14,
                    marginBottom: 14,
                    borderBottom: i < snapshot.manifest_entries.length - 1 ? '1px solid #F0E9D9' : 'none',
                  }}
                >
                  <div style={{ fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.06em', color: '#7A5A12', marginBottom: 4 }}>
                    {entry.section}
                  </div>
                  <div style={{ fontSize: 13, fontWeight: 600, color: '#3C4A5E', marginBottom: 4 }}>
                    {entry.field}
                  </div>
                  <div style={{ fontSize: 15, lineHeight: 1.5, color: '#0F1629', marginBottom: 4 }}>
                    {entry.value || <em>(not provided)</em>}
                  </div>
                  <div style={{ fontSize: 11, fontStyle: 'italic', color: '#6B7280' }}>
                    Source: {entry.source_step}
                  </div>
                </div>
              ))}
            </article>
          </>
        )}

        {/* Prime Directive (locked, verbatim) — always shown so the
            reader can verify both authenticity AND the platform's
            operating contract at the moment of PDF generation. */}
        <div
          data-testid="verify-prime-directive"
          style={{
            background: '#FFFFFF',
            border: '1px solid #E5DDC8',
            borderRadius: 12,
            padding: '32px 28px',
            boxShadow: '0 1px 2px rgba(15,22,41,0.04), 0 12px 32px rgba(15,22,41,0.06)',
          }}
        >
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, padding: '6px 14px', background: '#F5EBD3', border: '1px solid #D4AF37', borderRadius: 999, fontSize: 12, letterSpacing: '0.08em', textTransform: 'uppercase', fontWeight: 700, color: '#7A5A12', marginBottom: 16 }}>
            <Lock size={12} strokeWidth={2.5} />
            CarryOn Prime Directive — Locked {directive.locked_at}
          </div>
          <p style={{ fontSize: 16, lineHeight: 1.6, fontWeight: 600, margin: '0 0 16px 0' }}>
            {directive.opening}
          </p>
          <p style={{ fontSize: 14, lineHeight: 1.65, margin: '0 0 14px 0', color: '#3C4A5E' }}>
            {directive.legacy_mandate}
          </p>
          <p style={{ fontSize: 14, lineHeight: 1.65, margin: '0 0 20px 0', color: '#3C4A5E' }}>
            {directive.inclusivity_mandate}
          </p>
          <p style={{ fontSize: 12, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.06em', color: '#7A5A12', margin: '0 0 10px 0' }}>
            {directive.priority_preamble}
          </p>
          <ol style={{ paddingLeft: 20, margin: '0', fontSize: 14, lineHeight: 1.7 }}>
            {directive.priorities.map((p) => (
              <li key={p.n} style={{ marginBottom: 6 }}>{p.text}</li>
            ))}
          </ol>
        </div>

        <div style={{ marginTop: 32, display: 'flex', flexWrap: 'wrap', gap: 18, fontSize: 13 }}>
          <Link to="/our-promise" data-testid="verify-link-our-promise" style={{ color: '#0F1629', textDecoration: 'underline' }}>
            Our Promise (full)
          </Link>
          <Link to="/about" data-testid="verify-link-about" style={{ color: '#0F1629', textDecoration: 'underline' }}>
            About CarryOn
          </Link>
          <a href={`${API_URL}/verify/${encodeURIComponent(hash)}`} data-testid="verify-link-api" style={{ color: '#0F1629', textDecoration: 'underline', display: 'inline-flex', alignItems: 'center', gap: 4 }}>
            Raw API <ExternalLink size={12} />
          </a>
        </div>
      </div>
    </div>
  );
};

export default VerifyPage;
