/**
 * EntitiesPrintPage — letter-format printable view of the Entities &
 * Structures org chart.
 *
 * Opens in a new tab from the toolbar Print button. Renders a static
 * SVG (no React drag/zoom plumbing) so the browser's "Save as PDF"
 * pipeline produces a clean vector PDF that scales infinitely. Auto-
 * triggers `window.print()` once layout settles so the user lands on
 * the OS print dialog instantly.
 *
 * Page layout (letter / 8.5×11):
 *   ┌──────────────────────────────────────┐
 *   │  CarryOn™  — Entities & Structures   │  ← header
 *   │  Smith Family Trust • Mar 14, 2026   │
 *   ├──────────────────────────────────────┤
 *   │                                      │
 *   │        [centered SVG of tree]        │
 *   │                                      │
 *   ├──────────────────────────────────────┤
 *   │  Generated by CarryOn • carryon.us   │  ← footer
 *   └──────────────────────────────────────┘
 *
 * The SVG uses `viewBox` + `preserveAspectRatio="xMidYMid meet"` so it
 * fills the usable area of the page, centered, regardless of how
 * wide/tall the user's tree turned out. Legend is rendered as part of
 * the SVG so it prints at the same scale and at the position the user
 * dragged it to in the live chart.
 */
import React, { useEffect, useMemo, useState } from 'react';
import ReactDOM from 'react-dom';
import { useParams, useNavigate } from 'react-router-dom';
import axios from 'axios';
import { ChevronLeft, Printer, Maximize2, AlignVerticalJustifyCenter } from 'lucide-react';
import { useAuth } from '../../contexts/AuthContext';
import { API_URL } from '../../config';
import {
  buildGraph,
  computeInitialLayout,
  routeEdge,
  polylineToRoundedPath,
  PRINT_TILE_DIMENSIONS,
} from '../../components/financial/entities/EntityOrgChart';
import {
  ROLE_PALETTE,
  ROLE_OPTIONS,
  BUCKETS as ENTITY_BUCKETS,
  getTypeMeta,
  getEntityPalette,
  getBucketMeta,
  PALETTE,
} from '../../config/entityCatalog';
import { LEGEND_W } from '../../components/financial/entities/EntityLegend';

const { ENTITY_W, ENTITY_H, PERSON_W, PERSON_H, CORNER_R } = PRINT_TILE_DIMENSIONS;

// Lucide icon path data (24x24 viewBox, stroke-only) for the bucket
// indicators on entity tiles. Matches the live platform's
// EntityOrgChart.js which renders these same icons via lucide-react.
// We inline the path data here so the printed SVG is self-contained
// (no React-tree lookups during static SVG rendering).
const BUCKET_ICON_PATHS = {
  business: (
    <>
      <rect x="4" y="2" width="16" height="20" rx="2" ry="2" />
      <path d="M9 22v-4h6v4" />
      <circle cx="8" cy="6" r="0.6" /><circle cx="12" cy="6" r="0.6" /><circle cx="16" cy="6" r="0.6" />
      <circle cx="8" cy="10" r="0.6" /><circle cx="12" cy="10" r="0.6" /><circle cx="16" cy="10" r="0.6" />
      <circle cx="8" cy="14" r="0.6" /><circle cx="12" cy="14" r="0.6" /><circle cx="16" cy="14" r="0.6" />
    </>
  ),
  trust: (
    <path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z" />
  ),
  charity: (
    <>
      <line x1="3" x2="21" y1="22" y2="22" />
      <line x1="6" x2="6" y1="18" y2="11" />
      <line x1="10" x2="10" y1="18" y2="11" />
      <line x1="14" x2="14" y1="18" y2="11" />
      <line x1="18" x2="18" y1="18" y2="11" />
      <polygon points="12 2 20 7 4 7" />
    </>
  ),
  property: (
    <>
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </>
  ),
  external_person: (
    <>
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </>
  ),
  specialized: (
    <>
      <circle cx="12" cy="12" r="3" />
      <path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z" />
    </>
  ),
};

const EQUITY_ROLE_IDS = new Set([
  'owner', 'member', 'shareholder', 'gp', 'lp',
  'joint_tenant', 'tenant_in_common', 'community_property',
]);
const ROLE_LABEL = new Map(ROLE_OPTIONS.map((r) => [r.id, r.label]));

const fmtDate = (d = new Date()) =>
  d.toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' });

// Page-1 SVG content dimensions (inches) for each orientation. The
// values represent the USABLE area for the org-chart SVG inside a
// US Letter page: page size minus padding (0.3in) minus the header
// strip (~0.7in) minus the footer strip (~0.5in).
//   • Portrait  : 8.5 × 11   →  svg 7.9 × 8.2 in   (matches the
//                 historical single-page layout; preserves prior
//                 pdf appearance when users pick portrait).
//   • Landscape : 11  × 8.5  →  svg 10.4 × 6.7 in  (default — gives
//                 the widest possible tree per user pitch demo
//                 request).
// We keep these in CSS inches because iOS Safari's print engine
// honors absolute inch units inside @media print but mangles
// percentage-based SVG sizing.
const PAGE1_DIMS = {
  landscape: { pageW: 11,  pageH: 8.5, svgW: 10.4, svgH: 6.7 },
  portrait:  { pageW: 8.5, pageH: 11,  svgW: 7.9,  svgH: 8.2 },
};

export default function EntitiesPrintPage() {
  const { estateId } = useParams();
  const navigate = useNavigate();
  const { user, getAuthHeaders } = useAuth();
  const [data, setData] = useState(null);
  const [beneficiaries, setBeneficiaries] = useState([]);
  const [estateName, setEstateName] = useState('');
  const [error, setError] = useState(null);
  // Page-1 orientation toggle. User picked landscape as the default
  // for their pitch deck (widest possible tree). Toggle button in
  // the screen-only toolbar lets them flip to portrait without a
  // re-load. Page 2+ (Beneficiary Blocks list) is always portrait —
  // letter portrait is the standard reading orientation for text
  // lists and the user explicitly asked for portrait there.
  const [page1Orientation, setPage1Orientation] = useState('landscape');

  // Fetch the chart payload (entities + people + relationships +
  // server-persisted overrides), the beneficiaries list (so spouse /
  // children / other named beneficiaries that participate in
  // relationships render as person tiles — exactly like the live
  // chart does), plus the estate name for the header.
  useEffect(() => {
    let alive = true;
    (async () => {
      try {
        const headers = getAuthHeaders();
        const [entitiesRes, estateRes, bensRes] = await Promise.all([
          axios.get(`${API_URL}/financial/entities/${estateId}`, headers),
          axios.get(`${API_URL}/estates/${estateId}`, headers).catch(() => ({ data: null })),
          axios.get(`${API_URL}/beneficiaries/${estateId}`, headers).catch(() => ({ data: [] })),
        ]);
        if (!alive) return;
        setData(entitiesRes.data || {});
        setBeneficiaries(Array.isArray(bensRes?.data) ? bensRes.data : []);
        setEstateName(estateRes?.data?.name || '');
      } catch (e) {
        if (!alive) return;
        setError(e?.response?.data?.detail || e?.message || 'Could not load chart data');
      }
    })();
    return () => { alive = false; };
  }, [estateId, getAuthHeaders]);

  // Compute layout + bbox once data lands.
  const layout = useMemo(() => {
    if (!data) return null;
    const graph = buildGraph({
      entities: data.entities || [],
      externals: data.external_people || [],
      relationships: data.relationships || [],
      beneficiaries,
      blocks: data.beneficiary_blocks || [],
      user,
    });
    const initial = computeInitialLayout(graph.nodes, graph.depth);
    const overrides = data.chart_layout || {};

    const positionOf = (key) => overrides[key] || initial.positions[key] || { x: 0, y: 0 };

    // Tile rects (real nodes + legend pseudo-tile so edges avoid it
    // and the bbox includes it).
    const tileRects = graph.nodes.map((n) => {
      const p = positionOf(n.key);
      return {
        key: n.key,
        x: p.x,
        y: p.y,
        w: n.w,
        h: n.h,
        node: n,
      };
    });

    // Compute the legend's REAL height the same way renderLegend()
    // does. The static LEGEND_H constant assumed a max-size legend —
    // when fewer roles/categories are present, the legend is shorter,
    // and conversely with many roles+categories it can exceed
    // LEGEND_H. Using the wrong height starves the bbox of vertical
    // room and clips the legend in the printed PDF.
    const headerH = 22;
    const rowH = 18;
    const presentRoleIds = new Set();
    (data.relationships || []).forEach((r) => { if (r.role) presentRoleIds.add(r.role); });
    const presentRolesCount = ROLE_OPTIONS.filter((r) => presentRoleIds.has(r.id)).length;
    const presentCategoryIds = new Set();
    (data.entities || []).forEach((e) => { if (e.category) presentCategoryIds.add(e.category); });
    const presentCategoriesCount = (ENTITY_BUCKETS || []).filter((b) => presentCategoryIds.has(b.id)).length;
    const nLegendRows = presentRolesCount + presentCategoriesCount + ((presentRolesCount && presentCategoriesCount) ? 1 : 0);
    const computedLegendH = Math.max(60, headerH + nLegendRows * rowH + 14);

    // Honor the user's saved legend position from the live chart —
    // they drag it where they want; the print just inherits the same
    // coordinates. Since the legend is rendered INSIDE the tree SVG,
    // the whole composition scales together via preserveAspectRatio.
    const legendPos = overrides.__legend__ || { x: -LEGEND_W - 24, y: 0 };
    tileRects.push({ key: '__legend__', x: legendPos.x, y: legendPos.y, w: LEGEND_W, h: computedLegendH });

    // Pre-route every edge so we can fold the routed polyline points
    // and the ownership-% badge box into the bbox. Edge routing
    // detours around obstacles via `hit.y + hit.h + 14` style jumps —
    // those bend points can extend FAR outside any single tile, so
    // bbox'ing tiles alone leaves edges (and their %-pills) clipped
    // in the printed PDF.
    const rectByKey = Object.fromEntries(tileRects.map((r) => [r.key, r]));

    const routedEdges = graph.edges.map((edge) => {
      const sR = rectByKey[edge.sourceKey];
      const tR = rectByKey[edge.targetKey];
      if (!sR || !tR) return null;
      const obstacles = tileRects.filter((r) => r.key !== sR.key && r.key !== tR.key);
      const { points, midPoint } = routeEdge(sR, tR, obstacles, edge.id);
      return { edge, points, midPoint };
    }).filter(Boolean);

    // BBox covering every tile + every routed edge point + every
    // ownership label box + a comfortable padding so strokes/labels
    // never clip at the edges of the SVG viewBox.
    const PAD = 32;
    let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
    const extend = (x, y) => {
      if (x < minX) minX = x;
      if (y < minY) minY = y;
      if (x > maxX) maxX = x;
      if (y > maxY) maxY = y;
    };
    tileRects.forEach((r) => {
      extend(r.x, r.y);
      extend(r.x + r.w, r.y + r.h);
    });
    routedEdges.forEach(({ edge, points, midPoint }) => {
      points.forEach((p) => extend(p.x, p.y));
      // Ownership % pill: 36×18 centered on midPoint.
      if (EQUITY_ROLE_IDS.has(edge.role) && edge.ownership_pct != null) {
        extend(midPoint.x - 18, midPoint.y - 9);
        extend(midPoint.x + 18, midPoint.y + 9);
      }
    });
    if (!isFinite(minX)) { minX = minY = 0; maxX = 800; maxY = 600; }

    const viewBox = {
      x: minX - PAD,
      y: minY - PAD,
      w: (maxX - minX) + 2 * PAD,
      h: (maxY - minY) + 2 * PAD,
    };

    // 12pt minimum print font enforcement.
    // The page SVG width/height changes with the user's orientation
    // toggle, so the `scale = min(PAGE_W/bbox.w, PAGE_H/bbox.h)`
    // factor — and therefore the `minFont` floor — is computed
    // *outside* this memo (in render) where the current orientation
    // is known. We just hand back the raw bbox here; render does the
    // fit-to-page math.

    return {
      nodes: graph.nodes,
      edges: graph.edges,
      routedEdges,
      tileRects,
      legendPos,
      computedLegendH,
      viewBox,
      relationships: data.relationships || [],
      entities: data.entities || [],
      blocks: data.beneficiary_blocks || [],
    };
  }, [data, user, beneficiaries]);

  // No auto-print: iOS Safari blocks programmatic window.print() that
  // isn't a direct response to a user tap, and re-rendering on memo
  // changes causes the "blocked from automatically printing" dialog
  // to re-pop forever. The user invokes printing via the Print chip
  // in the on-screen toolbar — that click IS a user gesture, so iOS
  // shows the share-sheet print UI cleanly with no warning.

  if (error) {
    return (
      <div style={{ padding: 32, fontFamily: 'system-ui, -apple-system, sans-serif', color: '#0f172a', background: '#ffffff', minHeight: '100vh' }}>
        <button
          type="button"
          onClick={() => navigate(-1)}
          style={{
            display: 'inline-flex', alignItems: 'center', gap: 6,
            padding: '8px 14px', borderRadius: 9999,
            border: '1px solid #B8860B', background: '#fffaf0',
            color: '#B8860B', fontSize: 13, fontWeight: 700, cursor: 'pointer',
            marginBottom: 16,
          }}
          data-testid="entity-print-back"
        >
          <ChevronLeft size={14} /> Back
        </button>
        <h1 style={{ marginTop: 0, fontSize: 20 }}>Could not generate print</h1>
        <p>{error}</p>
      </div>
    );
  }
  if (!layout) {
    return (
      <div style={{ padding: 32, fontFamily: 'system-ui, -apple-system, sans-serif', color: '#0f172a', background: '#ffffff', minHeight: '100vh' }}>
        <button
          type="button"
          onClick={() => navigate(-1)}
          style={{
            display: 'inline-flex', alignItems: 'center', gap: 6,
            padding: '8px 14px', borderRadius: 9999,
            border: '1px solid #B8860B', background: '#fffaf0',
            color: '#B8860B', fontSize: 13, fontWeight: 700, cursor: 'pointer',
            marginBottom: 16,
          }}
          data-testid="entity-print-back"
        >
          <ChevronLeft size={14} /> Back
        </button>
        Loading chart for printing…
      </div>
    );
  }

  const today = fmtDate();
  const presentRoles = (() => {
    const seen = new Set();
    layout.relationships.forEach((r) => { if (r.role) seen.add(r.role); });
    return ROLE_OPTIONS.filter((r) => seen.has(r.id));
  })();
  const presentCategories = (() => {
    const seen = new Set();
    layout.entities.forEach((e) => { if (e.category) seen.add(e.category); });
    return (ENTITY_BUCKETS || []).filter((b) => seen.has(b.id));
  })();

  // ── Static SVG renderer ──────────────────────────────────────────

  // Orientation-aware page-1 SVG dimensions (inches → user-units at
  // 100 user-units per inch). Recomputed each render so the toggle
  // re-renders instantly.
  const page1Dims = PAGE1_DIMS[page1Orientation] || PAGE1_DIMS.landscape;
  const PAGE_W = page1Dims.svgW * 100;
  const PAGE_H = page1Dims.svgH * 100;
  const bbScale = Math.min(
    PAGE_W / Math.max(layout.viewBox.w, 1),
    PAGE_H / Math.max(layout.viewBox.h, 1),
  );
  // 12pt minimum print font enforcement.
  // 1 user-unit prints at bbScale × (svgW_in / PAGE_W) × 72 pt
  //                     = bbScale × 0.01 × 72 = bbScale × 0.72 pt.
  // For text fontSize N to render at ≥ 12pt:
  //   N × bbScale × 0.72 ≥ 12   →   N ≥ 12 / (0.72 × bbScale) ≈ 16.667 / bbScale
  // We use 17 (rounded up to be safe — gives 12.24pt at bbScale=1)
  // so EVERY hard-coded fontSize honors the user's strict "no less
  // than 12 point font" rule, even after the chart shrinks to fit.
  const minFont = Math.ceil(17 / Math.max(bbScale, 0.01));

  // 12pt minimum-font helper. Every hard-coded fontSize in the SVG
  // below is wrapped in `mf(N)` so it can be bumped up when the chart
  // shrinks to fit a single page (per user's strict "no less than
  // 12pt in any text PDFs" rule).
  const mf = (n) => Math.max(n, minFont);

  const renderEdges = () => {
    return layout.routedEdges.map(({ edge, points, midPoint }) => {
      const role = ROLE_PALETTE[edge.role] || ROLE_PALETTE.owner;
      const isEquity = EQUITY_ROLE_IDS.has(edge.role);
      const stroke = isEquity ? '#B8860B' : role.color;
      const sw = isEquity && edge.ownership_pct ? Math.max(1.6, Math.min(3.4, edge.ownership_pct / 33)) : 1.8;
      const d = polylineToRoundedPath(points);
      return (
        <g key={edge.id}>
          <path
            d={d}
            fill="none"
            stroke={stroke}
            strokeWidth={sw}
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeDasharray={role.dash || undefined}
            opacity={0.95}
          />
          {isEquity && edge.ownership_pct != null && (
            <g transform={`translate(${midPoint.x - 18}, ${midPoint.y - 9})`}>
              <rect width="36" height="18" rx="9" fill="#fffaf0" stroke="#B8860B" strokeWidth="1" />
              <text x="18" y="13" textAnchor="middle" fontSize={mf(10)} fontWeight="700" fill="#B8860B">
                {Math.round(edge.ownership_pct)}%
              </text>
            </g>
          )}
        </g>
      );
    });
  };

  const renderTile = (rect) => {
    const n = rect.node;
    if (!n) return null;
    const isEntity = n.kind === 'entity';
    // Auto-clusters (kind=cluster) and named blocks (kind=block) share
    // the same teal composite-tile rendering — they're conceptually
    // identical artefacts (a group of beneficiaries attached to an
    // entity). Only the header label differs.
    const isCluster = n.kind === 'cluster' || n.kind === 'block';
    const isBlock = n.kind === 'block';
    const e = isEntity ? n.entity : null;
    const typeMeta = isEntity ? getTypeMeta(e.category, e.type) : null;
    const titleText = isEntity ? (e?.name || 'Entity') : (n.label || '');
    const subText = isEntity
      ? (typeMeta?.friendly || e?.type || '')
      : (n.sublabel || '');
    // Pull category palette + bucket meta from the live entity
    // catalog so the print SVG inherits the same color coding the
    // user sees on the platform (steel/indigo/champagne/teal/slate).
    const entityPalette = isEntity ? getEntityPalette(e) : null;
    const bucketMeta = isEntity ? getBucketMeta(e?.category) : null;
    const accentColor = entityPalette?.stroke || '#B8860B';
    const tileFill = '#FFFFFF';
    // Person tiles keep the soft gold border (matches platform).
    // Entity tiles get the bucket's accent color so business/trust/
    // charity/etc. are visually distinct at a glance.
    const tileStroke = isEntity ? accentColor : '#B8860B';
    const tileStrokeW = 1.3;
    const avatarColor = n.avatar_color || '#B8860B';
    const avatarBg = n.kind === 'user' ? '#FEF3C7' : '#FFFFFF';
    const photoUrl = !isCluster ? (n.photo || null) : null;
    const clipId = `print-avatar-clip-${n.key.replace(/[^a-zA-Z0-9]/g, '_')}`;
    const iconPaths = isEntity ? BUCKET_ICON_PATHS[bucketMeta?.id || 'specialized'] : null;
    return (
      <g key={n.key} transform={`translate(${rect.x}, ${rect.y})`}>
        {/* Tile background — entities only. Person tiles render
            borderless (just the avatar circle + name + role) so the
            print page matches the live chart, where people float on
            the canvas without a surrounding card. */}
        {isEntity && (
          <rect
            width={rect.w}
            height={rect.h}
            rx={CORNER_R}
            fill={tileFill}
            stroke={tileStroke}
            strokeWidth={tileStrokeW}
          />
        )}
        {/* Entity tile: Lucide bucket icon (left), then title + sub */}
        {isEntity && (
          <>
            {iconPaths && (
              <g
                transform={`translate(8, ${rect.h / 2 - 10}) scale(0.83)`}
                fill="none"
                stroke={accentColor}
                strokeWidth={2}
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                {iconPaths}
              </g>
            )}
            <text
              x={36}
              y={rect.h / 2 - 4}
              fontSize={mf(13)}
              fontWeight="700"
              fill="#0F172A"
            >
              {fitTruncate(titleText, rect.w - 36 - 8, mf(13))}
            </text>
            {subText && (
              <text
                x={36}
                y={rect.h / 2 + 12}
                fontSize={mf(10)}
                fontWeight="600"
                fill={accentColor}
              >
                {fitTruncate(subText, rect.w - 36 - 8, mf(10))}
              </text>
            )}
            {e?.formation_state && (
              <g transform={`translate(${36}, ${rect.h - 18})`}>
                <rect width="28" height="13" rx="6" fill="#FFFAF0" stroke={accentColor} strokeWidth={0.9} />
                <text x="14" y="9.5" textAnchor="middle" fontSize={mf(8)} fontWeight="700" fill={accentColor}>
                  {e.formation_state}
                </text>
              </g>
            )}
          </>
        )}
        {/* Cluster tile — composite box rendering every beneficiary
            of the parent entity as a half-size avatar (5 per row,
            staggered). Connected to the parent entity by a single
            line in the edge layer. */}
        {isCluster && (() => {
          const members = n.members || [];
          const CLUSTER_AVATAR_R = 16;
          const CLUSTER_SLOT_W = 50;
          const CLUSTER_SLOT_H = 60;
          const CLUSTER_COLS = 5;
          const CLUSTER_HEADER_H = 22;
          const CLUSTER_PAD_X = 10;
          const CLUSTER_PAD_Y = 8;
          const HALF_STEP = CLUSTER_SLOT_W / 2;
          const parentName = (data.entities || []).find((ent) => ent.id === n.id)?.name || '';
          return (
            <>
              <rect
                width={rect.w}
                height={rect.h}
                rx={CORNER_R}
                fill="#F0FDF9"
                stroke="#22C993"
                strokeWidth={1.3}
              />
              <text
                x={CLUSTER_PAD_X}
                y={14}
                fontSize={mf(9)}
                fontWeight="700"
                fill="#0F766E"
                style={{ textTransform: 'uppercase' }}
              >
                {fitTruncate(
                  isBlock
                    ? (n.name || 'Block')
                    : `${members.length} beneficiar${members.length === 1 ? 'y' : 'ies'} · ${parentName}`,
                  rect.w - CLUSTER_PAD_X * 2,
                  mf(9),
                )}
              </text>
              {members.map((m, i) => {
                const row = Math.floor(i / CLUSTER_COLS);
                const col = i % CLUSTER_COLS;
                const stagger = row % 2 === 1 ? HALF_STEP : 0;
                const slotX = CLUSTER_PAD_X + col * CLUSTER_SLOT_W + stagger;
                const slotY = CLUSTER_HEADER_H + CLUSTER_PAD_Y + row * CLUSTER_SLOT_H;
                const cx = slotX + CLUSTER_AVATAR_R + 2;
                const cy = slotY + CLUSTER_AVATAR_R + 2;
                const memberClip = `print-cluster-clip-${n.id}-${m.id}`;
                const initials = (m.first_name?.[0] || '?').toUpperCase();
                return (
                  <g key={m.id}>
                    <defs>
                      <clipPath id={memberClip}>
                        <circle cx={cx} cy={cy} r={CLUSTER_AVATAR_R - 1} />
                      </clipPath>
                    </defs>
                    <circle cx={cx} cy={cy} r={CLUSTER_AVATAR_R} fill="#FFFFFF" stroke={m.avatar_color || '#22C993'} strokeWidth={1.3} />
                    {m.photo ? (
                      <image
                        href={m.photo}
                        xlinkHref={m.photo}
                        x={cx - CLUSTER_AVATAR_R + 1}
                        y={cy - CLUSTER_AVATAR_R + 1}
                        width={(CLUSTER_AVATAR_R - 1) * 2}
                        height={(CLUSTER_AVATAR_R - 1) * 2}
                        preserveAspectRatio="xMidYMid slice"
                        clipPath={`url(#${memberClip})`}
                      />
                    ) : (
                      <text x={cx} y={cy + 4} textAnchor="middle" fontSize={mf(10)} fontWeight="700" fill="#0F766E">
                        {initials}
                      </text>
                    )}
                    <text
                      x={cx}
                      y={cy + CLUSTER_AVATAR_R + 10}
                      textAnchor="middle"
                      fontSize={mf(8)}
                      fontWeight="700"
                      fill="#0F172A"
                    >
                      {fitTruncate((m.first_name || '').split(' ')[0], CLUSTER_SLOT_W - 4, mf(8))}
                    </text>
                  </g>
                );
              })}
            </>
          );
        })()}
        {/* Person tile: avatar circle (with photo if present) + name + sub + role chips. */}
        {!isEntity && !isCluster && (
          <>
            <defs>
              <clipPath id={clipId}>
                <circle cx={rect.w / 2} cy={28} r={22} />
              </clipPath>
            </defs>
            {/* Avatar ring */}
            <circle
              cx={rect.w / 2}
              cy={28}
              r={23}
              fill={avatarBg}
              stroke={avatarColor}
              strokeWidth={1.8}
            />
            {photoUrl ? (
              <image
                href={photoUrl}
                xlinkHref={photoUrl}
                x={rect.w / 2 - 22}
                y={6}
                width={44}
                height={44}
                preserveAspectRatio="xMidYMid slice"
                clipPath={`url(#${clipId})`}
              />
            ) : (
              <text
                x={rect.w / 2}
                y={33}
                textAnchor="middle"
                fontSize={mf(14)}
                fontWeight="700"
                fill="#92400E"
              >
                {((n.label?.[0] || '') + (n.sublabel?.[0] || '')).toUpperCase().slice(0, 2)}
              </text>
            )}
            {/* Name */}
            <text
              x={rect.w / 2}
              y={68}
              textAnchor="middle"
              fontSize={mf(11)}
              fontWeight="700"
              fill="#0F172A"
            >
              {fitTruncate(titleText, rect.w, mf(11))}
            </text>
            {subText && (
              <text
                x={rect.w / 2}
                y={82}
                textAnchor="middle"
                fontSize={mf(9)}
                fill="#475569"
              >
                {fitTruncate(subText, rect.w, mf(9))}
              </text>
            )}
            {Array.isArray(n.titles) && n.titles.length > 0 && (
              <text
                x={rect.w / 2}
                y={98}
                textAnchor="middle"
                fontSize={mf(9)}
                fontWeight="700"
                fill={tileStroke}
              >
                {fitTruncate(n.titles.join(' · '), rect.w, mf(9))}
              </text>
            )}
          </>
        )}
      </g>
    );
  };

  // Legend rendered INSIDE the main tree SVG at the user's saved
  // drag position from the live chart. Because it's part of the same
  // SVG that gets scaled to fit the page (via preserveAspectRatio),
  // it always renders in the right place at the right size — no
  // separate absolute-positioning math needed.
  const renderLegend = () => {
    if (presentRoles.length === 0 && presentCategories.length === 0) return null;
    const lp = layout.legendPos;
    const headerH = 22;
    const rowH = 18;
    // Use the SAME computed height we baked into the bbox so the
    // legend always fits inside the SVG viewBox (no clipping).
    const computedH = layout.computedLegendH;
    return (
      <g transform={`translate(${lp.x}, ${lp.y})`}>
        <rect
          width={LEGEND_W}
          height={computedH}
          rx={12}
          fill="#ffffff"
          stroke="#B8860B"
          strokeWidth={1.4}
        />
        <text x={10} y={16} fontSize={mf(11)} fontWeight="700" fill="#B8860B" letterSpacing="0.06em">
          LEGEND
        </text>
        <line x1={0} x2={LEGEND_W} y1={headerH} y2={headerH} stroke="#B8860B" strokeOpacity={0.35} />
        {presentRoles.map((role, i) => {
          const palette = ROLE_PALETTE[role.id] || ROLE_PALETTE.owner;
          const isEquity = EQUITY_ROLE_IDS.has(role.id);
          const stroke = isEquity ? '#B8860B' : palette.color;
          const y = headerH + 14 + i * rowH;
          return (
            <g key={role.id}>
              <line
                x1={10} x2={42}
                y1={y - 3} y2={y - 3}
                stroke={stroke}
                strokeWidth={isEquity ? 2.2 : 1.8}
                strokeLinecap="round"
                strokeDasharray={palette.dash || undefined}
              />
              <text x={50} y={y} fontSize={mf(11)} fill="#0f172a">{role.label}</text>
            </g>
          );
        })}
        {presentRoles.length > 0 && presentCategories.length > 0 && (
          <line
            x1={6} x2={LEGEND_W - 6}
            y1={headerH + 8 + presentRoles.length * rowH}
            y2={headerH + 8 + presentRoles.length * rowH}
            stroke="#B8860B"
            strokeOpacity={0.18}
          />
        )}
        {presentCategories.map((b, i) => {
          const yOffset = headerH + 14 + presentRoles.length * rowH + (presentRoles.length ? rowH : 0) + i * rowH;
          const bucketColor = (PALETTE[b.accent] || PALETTE.slate).stroke;
          const iconPaths = BUCKET_ICON_PATHS[b.id];
          return (
            <g key={b.id}>
              {iconPaths ? (
                <g
                  transform={`translate(15, ${yOffset - 14}) scale(0.55)`}
                  fill="none"
                  stroke={bucketColor}
                  strokeWidth={2}
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  {iconPaths}
                </g>
              ) : (
                <circle cx={26} cy={yOffset - 3} r={5} fill={bucketColor} />
              )}
              <text x={42} y={yOffset} fontSize={mf(11)} fill="#0f172a">{b.label}</text>
            </g>
          );
        })}
      </g>
    );
  };

  return ReactDOM.createPortal(
    <div className="cfp-print-root">
      <style dangerouslySetInnerHTML={{ __html: `
        /* Named @page rules let us give page 1 (org chart) and page
           2+ (beneficiary blocks list) different orientations. The
           page-1 orientation is user-controllable via the toolbar
           toggle; page 2 is always portrait per the user spec. */
        @page page1 { size: letter ${page1Orientation}; margin: 0; }
        @page page2 { size: letter portrait; margin: 0; }
        @page { size: letter ${page1Orientation}; margin: 0; }

        @media print {
          html, body {
            background: #ffffff !important;
            margin: 0 !important;
            padding: 0 !important;
            /* No height/overflow locks — they would prevent page 2
               from rendering at all. The browser handles paging via
               our explicit page-break rules below. */
          }
          /* The print root is rendered via React portal AS A DIRECT
             CHILD OF <body>. That lets us hide every OTHER body
             child cleanly — incl. NetworkStatusBanner, PendingSyncChip,
             NotificationContainer, and the entire #root mount — so
             nothing they render adds height to the print document. */
          body > *:not(.cfp-print-root) {
            display: none !important;
          }
          .cfp-print-root {
            color: #0f172a !important;
            display: block !important;
            background: #ffffff !important;
            margin: 0 !important;
            padding: 0 !important;
            width: auto !important;
            height: auto !important;
            min-height: 0 !important;
            max-height: none !important;
            overflow: visible !important;
            position: static !important;
          }

          /* Common page wrapper — each .cfp-print-page represents
             one (or more, for page 2 if the list overflows) physical
             pages. */
          .cfp-print-page {
            display: block !important;
            box-sizing: border-box !important;
            margin: 0 !important;
            background: #ffffff !important;
            color: #0f172a !important;
          }

          /* Page 1 — Org Chart. Uses orientation-specific named page
             rule so the printer flips paper for us. Hard size in
             inches matches the @page so the SVG fills it perfectly.
             page-break-after forces a fresh sheet for page 2. */
          .cfp-print-page-1 {
            page: page1;
            width: ${page1Dims.pageW}in !important;
            height: ${page1Dims.pageH}in !important;
            padding: 0.3in !important;
            overflow: hidden !important;
            page-break-after: always !important;
            break-after: page !important;
            page-break-inside: avoid !important;
            break-inside: avoid !important;
          }

          /* Page 2+ — Beneficiary Blocks list. ALWAYS portrait. We
             let the block list flow across multiple sheets naturally
             (page-break-inside: auto on the wrapper) but keep each
             block-row intact (avoid breaking a single block across
             pages). */
          .cfp-print-page-2 {
            page: page2;
            width: 8.5in !important;
            min-height: 11in !important;
            padding: 0.5in !important;
            page-break-before: always !important;
            break-before: page !important;
            page-break-inside: auto !important;
            break-inside: auto !important;
          }

          /* Header strip on each printed page. Sized so the SVG /
             list area below has predictable room. */
          .cfp-print-page-1 .cfp-print-header,
          .cfp-print-page-2 .cfp-print-header {
            display: block !important;
            margin: 0 0 0.1in 0 !important;
            padding: 0 0 0.08in 0 !important;
            border-bottom: 1px solid #B8860B !important;
            overflow: hidden !important;
          }
          .cfp-print-page-1 .cfp-print-header { height: 0.65in !important; max-height: 0.65in !important; }
          .cfp-print-page-1 .cfp-print-header h1 {
            margin: 0 !important;
            font-size: 18pt !important;
            font-weight: 800 !important;
            color: #B8860B !important;
            line-height: 1.1 !important;
          }
          .cfp-print-page-1 .cfp-print-header .subtitle {
            margin-top: 0.04in !important;
            font-size: 12pt !important;
            color: #475569 !important;
          }
          .cfp-print-page-2 .cfp-print-header h1 {
            margin: 0 !important;
            font-size: 20pt !important;
            font-weight: 800 !important;
            color: #B8860B !important;
            line-height: 1.1 !important;
          }
          .cfp-print-page-2 .cfp-print-header .subtitle {
            margin-top: 0.05in !important;
            font-size: 12pt !important;
            color: #475569 !important;
          }

          /* SVG wrap on page 1 — hard inch sizing matches our viewBox
             scale calc so the tree renders at exactly the size we
             computed. */
          .cfp-print-svg-wrap {
            display: block !important;
            width: ${page1Dims.svgW}in !important;
            height: ${page1Dims.svgH}in !important;
            max-width: ${page1Dims.svgW}in !important;
            max-height: ${page1Dims.svgH}in !important;
            min-width: ${page1Dims.svgW}in !important;
            min-height: ${page1Dims.svgH}in !important;
            margin: 0 auto !important;
            padding: 0 !important;
            overflow: hidden !important;
            position: relative !important;
            page-break-inside: avoid !important;
            break-inside: avoid !important;
          }
          .cfp-print-svg-wrap svg {
            display: block !important;
            width: ${page1Dims.svgW}in !important;
            height: ${page1Dims.svgH}in !important;
            margin: 0 !important;
            padding: 0 !important;
          }

          /* Page 2 — Beneficiary Blocks list typography & spacing.
             All sizes are ≥ 12pt per the user's strict requirement. */
          .cfp-print-blocks-list {
            font-size: 12pt !important;
            line-height: 1.4 !important;
            color: #0f172a !important;
            margin-top: 0.15in !important;
          }
          .cfp-print-block-row {
            padding: 0.12in 0 !important;
            border-bottom: 1px solid #e2e8f0 !important;
            page-break-inside: avoid !important;
            break-inside: avoid !important;
          }
          .cfp-print-block-row:last-child { border-bottom: none !important; }
          .cfp-print-block-name {
            font-size: 14pt !important;
            font-weight: 700 !important;
            color: #0F172A !important;
            margin-bottom: 0.06in !important;
          }
          .cfp-print-block-line {
            font-size: 12pt !important;
            color: #334155 !important;
            margin: 0.04in 0 !important;
          }
          .cfp-print-block-label {
            font-weight: 700 !important;
            color: #B8860B !important;
          }

          /* iOS Safari renders its own footer (URL + date + page
             number) on every printed page; hide our in-document
             footer to avoid the duplicate. */
          .cfp-print-footer { display: none !important; }
          .cfp-print-toolbar { display: none !important; }
        }

        /* Screen preview styles. Each printed page is mocked as a
           card so the user sees a faithful preview before printing.
           We force an opaque light background on the root so the
           app's dark theme (which lives on #root, a sibling in <body>)
           doesn't bleed through. */
        body { background: #f4f4f4 !important; margin: 0; }
        .cfp-print-root {
          font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
          color: #0f172a !important;
          background: #f4f4f4 !important;
          width: 100vw !important;
          min-height: 100vh;
          min-height: 100dvh;
          margin: 0 !important;
          padding: 0 12px 12px 12px !important;
          padding-bottom: max(12px, env(safe-area-inset-bottom)) !important;
          box-sizing: border-box;
          display: flex;
          flex-direction: column;
          position: fixed !important;
          inset: 0 !important;
          z-index: 99999 !important;
          overflow: auto;
          -webkit-overflow-scrolling: touch;
        }
        .cfp-print-page { color: #0f172a !important; }
        .cfp-print-header h1 { color: #B8860B !important; }
        .cfp-print-header .subtitle { color: #475569 !important; }
        .cfp-print-toolbar button { box-shadow: none !important; }
        .cfp-print-toolbar {
          display: flex;
          gap: 8px;
          padding: 12px 0;
          padding-top: max(12px, env(safe-area-inset-top));
          padding-left: max(12px, env(safe-area-inset-left));
          padding-right: max(12px, env(safe-area-inset-right));
          position: sticky;
          top: 0;
          background: #f4f4f4;
          z-index: 10;
          flex-wrap: wrap;
        }
        .cfp-print-toolbar button {
          display: inline-flex; align-items: center; gap: 6px;
          padding: 8px 14px; border-radius: 9999px;
          font-size: 13px; font-weight: 700;
          cursor: pointer;
        }
        .cfp-print-back {
          background: #ffffff; color: #0f172a; border: 1px solid #cbd5e1;
        }
        .cfp-print-orient {
          background: #ffffff; color: #0f172a; border: 1px solid #cbd5e1;
        }
        .cfp-print-reprint {
          background: #fffaf0; color: #B8860B; border: 1px solid #B8860B;
        }

        /* On-screen page cards (mock the printed sheets). */
        .cfp-print-page {
          background: #ffffff;
          margin: 12px auto;
          box-shadow: 0 4px 18px rgba(15, 23, 42, 0.08);
          box-sizing: border-box;
          color: #0f172a;
          width: 100%;
        }
        .cfp-print-page-1 {
          max-width: ${page1Dims.pageW}in;
          aspect-ratio: ${page1Dims.pageW} / ${page1Dims.pageH};
          padding: 0.3in;
          display: flex;
          flex-direction: column;
        }
        .cfp-print-page-2 {
          max-width: 8.5in;
          padding: 0.5in;
        }
        .cfp-print-header {
          border-bottom: 2px solid #B8860B;
          padding-bottom: 8px;
          margin-bottom: 12px;
        }
        .cfp-print-header h1 {
          margin: 0;
          font-size: 20px;
          font-weight: 800;
          color: #B8860B;
          letter-spacing: 0.02em;
        }
        .cfp-print-header .subtitle {
          margin-top: 4px;
          font-size: 13px;
          color: #475569;
        }
        .cfp-print-page-2 .cfp-print-header h1 { font-size: 22px; }

        .cfp-print-svg-wrap {
          flex: 1 1 auto;
          min-height: 0;
          width: 100%;
          display: block;
          position: relative;
        }
        .cfp-print-svg-wrap svg {
          width: 100%;
          height: 100%;
          display: block;
        }

        .cfp-print-blocks-list {
          margin-top: 8px;
          font-size: 16px;
          line-height: 1.45;
          color: #0f172a;
        }
        .cfp-print-block-row {
          padding: 12px 0;
          border-bottom: 1px solid #e2e8f0;
        }
        .cfp-print-block-row:last-child { border-bottom: none; }
        .cfp-print-block-name {
          font-size: 18px;
          font-weight: 700;
          color: #0F172A;
          margin-bottom: 6px;
        }
        .cfp-print-block-line {
          font-size: 16px;
          color: #334155;
          margin: 4px 0;
        }
        .cfp-print-block-label {
          font-weight: 700;
          color: #B8860B;
        }

        .cfp-print-footer {
          margin-top: 12px;
          padding-top: 8px;
          border-top: 1px solid #e2e8f0;
          font-size: 10px;
          color: #94a3b8;
          display: flex;
          justify-content: space-between;
        }
      `}} />

      {/* Screen-only toolbar — gives the user an obvious escape route
          on iOS standalone PWA where the OS print dialog cancels and
          leaves them on this page. Hidden via @media print so the
          PDF stays clean. */}
      <div className="cfp-print-toolbar">
        <button
          type="button"
          className="cfp-print-back"
          onClick={() => navigate(-1)}
          data-testid="entity-print-back"
        >
          <ChevronLeft size={14} /> Back
        </button>
        <button
          type="button"
          className="cfp-print-orient"
          onClick={() => setPage1Orientation((o) => (o === 'landscape' ? 'portrait' : 'landscape'))}
          data-testid="entity-print-orient-toggle"
          title="Toggle page-1 orientation"
        >
          {page1Orientation === 'landscape' ? (
            <><Maximize2 size={14} /> Landscape</>
          ) : (
            <><AlignVerticalJustifyCenter size={14} /> Portrait</>
          )}
        </button>
        <button
          type="button"
          className="cfp-print-reprint"
          onClick={() => { try { window.print(); } catch { /* user dismissed */ } }}
          data-testid="entity-print-reprint"
        >
          <Printer size={14} /> Print
        </button>
      </div>

      <div className="cfp-print-page cfp-print-page-1">
        <div className="cfp-print-header">
          <h1>Entities &amp; Structures</h1>
          <div className="subtitle">
            {estateName ? `${estateName} • ` : ''}{today}
          </div>
        </div>

        <div className="cfp-print-svg-wrap">
          {(() => {
            // iOS Safari's print engine silently ignores `preserveAspectRatio`
            // on SVG when the surrounding wrapper has hard inch dimensions —
            // so tree content authored in user-space coordinates leaks past
            // the right/bottom edges of the page. Sidestep the engine by
            // using a FIXED pixel-unit viewBox (PAGE_W × PAGE_H — the
            // 100-px-per-inch equivalent of our physical SVG) and applying
            // the bbox-fit scale + center-translate ourselves on an outer
            // <g>. This makes the tree render *deterministically* at the
            // size we computed, regardless of how the browser interprets
            // the outer <svg> sizing.
            const bb = layout.viewBox;
            const tx = (PAGE_W - bb.w * bbScale) / 2 - bb.x * bbScale;
            const ty = (PAGE_H - bb.h * bbScale) / 2 - bb.y * bbScale;
            return (
              <svg
                width={`${page1Dims.svgW}in`}
                height={`${page1Dims.svgH}in`}
                viewBox={`0 0 ${PAGE_W} ${PAGE_H}`}
                preserveAspectRatio="xMidYMid meet"
                xmlns="http://www.w3.org/2000/svg"
                data-testid="entity-print-svg"
                style={{ display: 'block' }}
              >
                <g transform={`translate(${tx} ${ty}) scale(${bbScale})`}>
                  {renderEdges()}
                  {layout.tileRects.filter((r) => r.key !== '__legend__').map(renderTile)}
                  {renderLegend()}
                </g>
              </svg>
            );
          })()}
        </div>

        <div className="cfp-print-footer">
          <span>Generated by CarryOn™</span>
          <span>carryon.us</span>
        </div>
      </div>

      {/* Page 2+ — Beneficiary Blocks summary list. Only renders when
          the estate has at least one block. Flows naturally across
          additional pages if the list is long. Every text element on
          this page is set to ≥ 12pt per the user's "no less than 12
          point font anywhere in any text PDFs" requirement. */}
      {(layout.blocks || []).length > 0 && (
        <div className="cfp-print-page cfp-print-page-2" data-testid="entity-print-blocks-page">
          <div className="cfp-print-header">
            <h1>Beneficiary Blocks</h1>
            <div className="subtitle">
              {estateName ? `${estateName} • ` : ''}{today} • {(layout.blocks || []).length} block{(layout.blocks || []).length === 1 ? '' : 's'}
            </div>
          </div>
          <div className="cfp-print-blocks-list">
            {(layout.blocks || []).map((b) => {
              const attachedEntityNames = (layout.relationships || [])
                .filter((r) => r.source_type === 'beneficiary_block'
                  && r.source_id === b.id
                  && r.target_type === 'entity'
                  && r.role === 'beneficiary')
                .map((r) => (layout.entities || []).find((e) => e.id === r.target_id)?.name)
                .filter(Boolean);
              const memberLabels = (b.members || []).map((m) => {
                if (m.kind === 'beneficiary') {
                  const ben = (beneficiaries || []).find((bb) => bb.id === m.id);
                  return ben ? `${ben.first_name || ''} ${ben.last_name || ''}`.trim() : null;
                }
                if (m.kind === 'external_person') {
                  const ep = (data?.external_people || []).find((p) => p.id === m.id);
                  return ep ? `${ep.first_name || ''} ${ep.last_name || ''}`.trim() : null;
                }
                if (m.kind === 'user') {
                  return user ? `${user.first_name || ''} ${user.last_name || ''}`.trim() || 'You' : 'You';
                }
                return null;
              }).filter(Boolean);
              return (
                <div key={b.id} className="cfp-print-block-row" data-testid={`entity-print-block-row-${b.id}`}>
                  <div className="cfp-print-block-name">{b.name}</div>
                  <div className="cfp-print-block-line">
                    <span className="cfp-print-block-label">Members ({memberLabels.length}):</span>{' '}
                    {memberLabels.length === 0 ? '—' : memberLabels.join(', ')}
                  </div>
                  <div className="cfp-print-block-line">
                    <span className="cfp-print-block-label">Attached to ({attachedEntityNames.length}):</span>{' '}
                    {attachedEntityNames.length === 0 ? 'not attached to any entity yet' : attachedEntityNames.join(', ')}
                  </div>
                </div>
              );
            })}
          </div>
          <div className="cfp-print-footer">
            <span>Generated by CarryOn™</span>
            <span>carryon.us</span>
          </div>
        </div>
      )}
    </div>,
    document.body
  );
}

function truncate(s, n) {
  if (!s) return '';
  return s.length <= n ? s : s.slice(0, n - 1) + '…';
}

// Width-aware truncation. Computes the max number of glyphs that
// will fit inside `widthUserUnits` at the given SVG fontSize. We use
// a 0.55 width factor (avg glyph is ~55% of the font size for the
// system-ui stack used in print). The caller decides the width
// budget; this helper just turns it into a safe character count.
// This matters because `mf()` inflates fontSize when the chart
// shrinks to fit (to keep the 12pt-min rule), and at high inflation
// the static "truncate(text, 24)" calls overflow the tile.
function fitTruncate(s, widthUserUnits, fontSizeUserUnits, hardMin = 4) {
  if (!s) return '';
  const maxChars = Math.max(hardMin, Math.floor(widthUserUnits / (fontSizeUserUnits * 0.55)));
  return truncate(s, maxChars);
}
