/**
 * EntitiesPrintPage — letter-format printable view of the Entities &
 * Structures org chart.
 *
 * Opens in a new tab from the toolbar Print button. Renders a static
 * SVG (no React drag/zoom plumbing) so the browser's "Save as PDF"
 * pipeline produces a clean vector PDF that scales infinitely. Auto-
 * triggers `window.print()` once layout settles so the user lands on
 * the OS print dialog instantly.
 *
 * Page layout (letter / 8.5×11):
 *   ┌──────────────────────────────────────┐
 *   │  CarryOn™  — Entities & Structures   │  ← header
 *   │  Smith Family Trust • Mar 14, 2026   │
 *   ├──────────────────────────────────────┤
 *   │                                      │
 *   │        [centered SVG of tree]        │
 *   │                                      │
 *   ├──────────────────────────────────────┤
 *   │  Generated by CarryOn • carryon.us   │  ← footer
 *   └──────────────────────────────────────┘
 *
 * The SVG uses `viewBox` + `preserveAspectRatio="xMidYMid meet"` so it
 * fills the usable area of the page, centered, regardless of how
 * wide/tall the user's tree turned out. Legend is rendered as part of
 * the SVG so it prints at the same scale and at the position the user
 * dragged it to in the live chart.
 */
import React, { useEffect, useMemo, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import axios from 'axios';
import { ChevronLeft, Printer } from 'lucide-react';
import { useAuth } from '../../contexts/AuthContext';
import { API_URL } from '../../config';
import {
  buildGraph,
  computeInitialLayout,
  routeEdge,
  polylineToRoundedPath,
  PRINT_TILE_DIMENSIONS,
} from '../../components/financial/entities/EntityOrgChart';
import {
  ROLE_PALETTE,
  ROLE_OPTIONS,
  BUCKETS as ENTITY_BUCKETS,
  getTypeMeta,
} from '../../config/entityCatalog';
import { LEGEND_W, LEGEND_H } from '../../components/financial/entities/EntityLegend';

const { ENTITY_W, ENTITY_H, PERSON_W, PERSON_H, CORNER_R } = PRINT_TILE_DIMENSIONS;

const EQUITY_ROLE_IDS = new Set([
  'owner', 'member', 'shareholder', 'gp', 'lp',
  'joint_tenant', 'tenant_in_common', 'community_property',
]);
const ROLE_LABEL = new Map(ROLE_OPTIONS.map((r) => [r.id, r.label]));

const fmtDate = (d = new Date()) =>
  d.toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' });

export default function EntitiesPrintPage() {
  const { estateId } = useParams();
  const navigate = useNavigate();
  const { user, getAuthHeaders } = useAuth();
  const [data, setData] = useState(null);
  const [estateName, setEstateName] = useState('');
  const [error, setError] = useState(null);

  // Fetch the chart payload (entities + people + relationships +
  // server-persisted overrides) plus the estate name for the header.
  useEffect(() => {
    let alive = true;
    (async () => {
      try {
        const headers = getAuthHeaders();
        const [entitiesRes, estateRes] = await Promise.all([
          axios.get(`${API_URL}/financial/entities/${estateId}`, headers),
          axios.get(`${API_URL}/estates/${estateId}`, headers).catch(() => ({ data: null })),
        ]);
        if (!alive) return;
        setData(entitiesRes.data || {});
        setEstateName(estateRes?.data?.name || '');
      } catch (e) {
        if (!alive) return;
        setError(e?.response?.data?.detail || e?.message || 'Could not load chart data');
      }
    })();
    return () => { alive = false; };
  }, [estateId, getAuthHeaders]);

  // Compute layout + bbox once data lands.
  const layout = useMemo(() => {
    if (!data) return null;
    const beneficiaries = []; // benefactor view → no extra benef nodes; relationships drive everything
    const graph = buildGraph({
      entities: data.entities || [],
      externals: data.external_people || [],
      relationships: data.relationships || [],
      beneficiaries,
      user,
    });
    const initial = computeInitialLayout(graph.nodes, graph.depth);
    const overrides = data.chart_layout || {};

    const positionOf = (key) => overrides[key] || initial.positions[key] || { x: 0, y: 0 };

    // Tile rects (real nodes + legend pseudo-tile so edges avoid it
    // and the bbox includes it).
    const tileRects = graph.nodes.map((n) => {
      const p = positionOf(n.key);
      return { key: n.key, x: p.x, y: p.y, w: n.w, h: n.h, node: n };
    });
    const legendPos = overrides.__legend__ || { x: -LEGEND_W - 24, y: 0 };
    tileRects.push({ key: '__legend__', x: legendPos.x, y: legendPos.y, w: LEGEND_W, h: LEGEND_H });

    // BBox covering every tile + a comfortable padding so strokes
    // don't clip on the edges of the SVG viewBox.
    const PAD = 24;
    let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
    tileRects.forEach((r) => {
      if (r.x < minX) minX = r.x;
      if (r.y < minY) minY = r.y;
      if (r.x + r.w > maxX) maxX = r.x + r.w;
      if (r.y + r.h > maxY) maxY = r.y + r.h;
    });
    if (!isFinite(minX)) { minX = minY = 0; maxX = 800; maxY = 600; }

    return {
      nodes: graph.nodes,
      edges: graph.edges,
      tileRects,
      legendPos,
      viewBox: {
        x: minX - PAD,
        y: minY - PAD,
        w: (maxX - minX) + 2 * PAD,
        h: (maxY - minY) + 2 * PAD,
      },
      relationships: data.relationships || [],
      entities: data.entities || [],
    };
  }, [data, user]);

  // No auto-print: iOS Safari blocks programmatic window.print() that
  // isn't a direct response to a user tap, and re-rendering on memo
  // changes causes the "blocked from automatically printing" dialog
  // to re-pop forever. The user invokes printing via the Print chip
  // in the on-screen toolbar — that click IS a user gesture, so iOS
  // shows the share-sheet print UI cleanly with no warning.

  if (error) {
    return (
      <div style={{ padding: 32, fontFamily: 'system-ui, -apple-system, sans-serif', color: '#0f172a', background: '#ffffff', minHeight: '100vh' }}>
        <button
          type="button"
          onClick={() => navigate(-1)}
          style={{
            display: 'inline-flex', alignItems: 'center', gap: 6,
            padding: '8px 14px', borderRadius: 9999,
            border: '1px solid #B8860B', background: '#fffaf0',
            color: '#B8860B', fontSize: 13, fontWeight: 700, cursor: 'pointer',
            marginBottom: 16,
          }}
          data-testid="entity-print-back"
        >
          <ChevronLeft size={14} /> Back
        </button>
        <h1 style={{ marginTop: 0, fontSize: 20 }}>Could not generate print</h1>
        <p>{error}</p>
      </div>
    );
  }
  if (!layout) {
    return (
      <div style={{ padding: 32, fontFamily: 'system-ui, -apple-system, sans-serif', color: '#0f172a', background: '#ffffff', minHeight: '100vh' }}>
        <button
          type="button"
          onClick={() => navigate(-1)}
          style={{
            display: 'inline-flex', alignItems: 'center', gap: 6,
            padding: '8px 14px', borderRadius: 9999,
            border: '1px solid #B8860B', background: '#fffaf0',
            color: '#B8860B', fontSize: 13, fontWeight: 700, cursor: 'pointer',
            marginBottom: 16,
          }}
          data-testid="entity-print-back"
        >
          <ChevronLeft size={14} /> Back
        </button>
        Loading chart for printing…
      </div>
    );
  }

  const today = fmtDate();
  const presentRoles = (() => {
    const seen = new Set();
    layout.relationships.forEach((r) => { if (r.role) seen.add(r.role); });
    return ROLE_OPTIONS.filter((r) => seen.has(r.id));
  })();
  const presentCategories = (() => {
    const seen = new Set();
    layout.entities.forEach((e) => { if (e.category) seen.add(e.category); });
    return (ENTITY_BUCKETS || []).filter((b) => seen.has(b.id));
  })();

  // ── Static SVG renderer ──────────────────────────────────────────
  const rectByKey = Object.fromEntries(layout.tileRects.map((r) => [r.key, r]));

  const renderEdges = () => {
    return layout.edges.map((edge) => {
      const sR = rectByKey[edge.sourceKey];
      const tR = rectByKey[edge.targetKey];
      if (!sR || !tR) return null;
      const obstacles = layout.tileRects.filter((r) => r.key !== sR.key && r.key !== tR.key);
      const { points, midPoint } = routeEdge(sR, tR, obstacles, edge.id);
      const role = ROLE_PALETTE[edge.role] || ROLE_PALETTE.owner;
      const isEquity = EQUITY_ROLE_IDS.has(edge.role);
      const stroke = isEquity ? '#B8860B' : role.color;
      const sw = isEquity && edge.ownership_pct ? Math.max(1.6, Math.min(3.4, edge.ownership_pct / 33)) : 1.8;
      const d = polylineToRoundedPath(points);
      return (
        <g key={edge.id}>
          <path
            d={d}
            fill="none"
            stroke={stroke}
            strokeWidth={sw}
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeDasharray={role.dash || undefined}
            opacity={0.95}
          />
          {isEquity && edge.ownership_pct != null && (
            <g transform={`translate(${midPoint.x - 18}, ${midPoint.y - 9})`}>
              <rect width="36" height="18" rx="9" fill="#fffaf0" stroke="#B8860B" strokeWidth="1" />
              <text x="18" y="13" textAnchor="middle" fontSize="10" fontWeight="700" fill="#B8860B">
                {Math.round(edge.ownership_pct)}%
              </text>
            </g>
          )}
        </g>
      );
    });
  };

  const renderTile = (rect) => {
    const n = rect.node;
    if (!n) return null;
    const isEntity = n.kind === 'entity';
    // Entity nodes don't have `label`/`sublabel` populated by buildGraph
    // (the live EntityTile reads `n.entity.name` / type-meta directly),
    // so for the static SVG we synthesize the same fields here.
    const e = isEntity ? n.entity : null;
    const typeMeta = isEntity ? getTypeMeta(e.category, e.type) : null;
    const titleText = isEntity ? (e?.name || 'Entity') : (n.label || '');
    const subText = isEntity
      ? (typeMeta?.friendly || e?.type || '')
      : (n.sublabel || '');
    const fill = '#ffffff';
    const stroke = '#1f2937';
    return (
      <g key={n.key} transform={`translate(${rect.x}, ${rect.y})`}>
        <rect
          width={rect.w}
          height={rect.h}
          rx={CORNER_R}
          fill={fill}
          stroke={stroke}
          strokeWidth={1.4}
        />
        {/* Title */}
        <text
          x={rect.w / 2}
          y={isEntity ? 30 : 60}
          textAnchor="middle"
          fontSize={isEntity ? 14 : 12}
          fontWeight="700"
          fill="#0f172a"
        >
          {truncate(titleText, isEntity ? 24 : 14)}
        </text>
        {/* Sublabel (entity friendly type / last name / "Outside party") */}
        {subText && (
          <text
            x={rect.w / 2}
            y={isEntity ? 50 : 76}
            textAnchor="middle"
            fontSize={11}
            fill="#475569"
          >
            {truncate(subText, isEntity ? 30 : 16)}
          </text>
        )}
        {/* For entity tiles: state pill */}
        {isEntity && e?.formation_state && (
          <g transform={`translate(${rect.w / 2 - 14}, ${64})`}>
            <rect width="28" height="16" rx="6" fill="#fffaf0" stroke="#B8860B" strokeWidth={1} />
            <text x="14" y="11" textAnchor="middle" fontSize="9" fontWeight="700" fill="#B8860B">
              {e.formation_state}
            </text>
          </g>
        )}
        {/* For people: role title chip(s) */}
        {!isEntity && Array.isArray(n.titles) && n.titles.length > 0 && (
          <text
            x={rect.w / 2}
            y={94}
            textAnchor="middle"
            fontSize={10}
            fontWeight="700"
            fill="#B8860B"
          >
            {truncate(n.titles.join(' · '), 18)}
          </text>
        )}
        {/* Avatar circle for people (initials) */}
        {!isEntity && (
          <g transform={`translate(${rect.w / 2 - 22}, ${4})`}>
            <circle cx="22" cy="22" r="22" fill="#fef3c7" stroke="#B8860B" strokeWidth={1.4} />
            <text x="22" y="27" textAnchor="middle" fontSize="13" fontWeight="700" fill="#92400e">
              {((n.label?.[0] || '') + (n.sublabel?.[0] || '')).toUpperCase().slice(0, 2)}
            </text>
          </g>
        )}
      </g>
    );
  };

  const renderLegend = () => {
    if (presentRoles.length === 0 && presentCategories.length === 0) return null;
    const lp = layout.legendPos;
    const headerH = 22;
    const rowH = 18;
    const nRows = presentRoles.length + presentCategories.length + (presentRoles.length && presentCategories.length ? 1 : 0);
    const computedH = headerH + nRows * rowH + 14;
    return (
      <g transform={`translate(${lp.x}, ${lp.y})`}>
        <rect
          width={LEGEND_W}
          height={Math.max(60, computedH)}
          rx={12}
          fill="#ffffff"
          stroke="#B8860B"
          strokeWidth={1.4}
        />
        <text x={10} y={16} fontSize={11} fontWeight="700" fill="#B8860B" letterSpacing="0.06em">
          LEGEND
        </text>
        <line x1={0} x2={LEGEND_W} y1={headerH} y2={headerH} stroke="#B8860B" strokeOpacity={0.35} />
        {presentRoles.map((role, i) => {
          const palette = ROLE_PALETTE[role.id] || ROLE_PALETTE.owner;
          const isEquity = EQUITY_ROLE_IDS.has(role.id);
          const stroke = isEquity ? '#B8860B' : palette.color;
          const y = headerH + 14 + i * rowH;
          return (
            <g key={role.id}>
              <line
                x1={10} x2={42}
                y1={y - 3} y2={y - 3}
                stroke={stroke}
                strokeWidth={isEquity ? 2.2 : 1.8}
                strokeLinecap="round"
                strokeDasharray={palette.dash || undefined}
              />
              <text x={50} y={y} fontSize={11} fill="#0f172a">{role.label}</text>
            </g>
          );
        })}
        {presentRoles.length > 0 && presentCategories.length > 0 && (
          <line
            x1={6} x2={LEGEND_W - 6}
            y1={headerH + 8 + presentRoles.length * rowH}
            y2={headerH + 8 + presentRoles.length * rowH}
            stroke="#B8860B"
            strokeOpacity={0.18}
          />
        )}
        {presentCategories.map((b, i) => {
          const yOffset = headerH + 14 + presentRoles.length * rowH + (presentRoles.length ? rowH : 0) + i * rowH;
          return (
            <g key={b.id}>
              <circle cx={26} cy={yOffset - 3} r={5} fill="#B8860B" />
              <text x={50} y={yOffset} fontSize={11} fill="#0f172a">{b.label}</text>
            </g>
          );
        })}
      </g>
    );
  };

  return (
    <div className="cfp-print-root">
      <style>{`
        @page { size: letter portrait; margin: 0; }
        @media print {
          html, body, #root {
            background: #ffffff !important;
            margin: 0 !important;
            padding: 0 !important;
            width: 8.5in !important;
            min-width: 8.5in !important;
            height: 11in !important;
            min-height: 0 !important;
            overflow: hidden !important;
          }
          /* Belt-and-suspenders: hide every element OUTSIDE our print
             root so a stray app-level wrapper (banner, devtools, etc.)
             can't push our content onto a second page. */
          body > *:not(#root),
          #root > *:not(.cfp-print-root) {
            display: none !important;
          }
          .cfp-print-root {
            color: #0f172a !important;
            display: block !important;
            width: 8.5in !important;
            min-width: 8.5in !important;
            max-width: 8.5in !important;
            height: 11in !important;
            min-height: 11in !important;
            max-height: 11in !important;
            padding: 0.4in !important;
            margin: 0 !important;
            box-sizing: border-box !important;
            overflow: hidden !important;
            page-break-inside: avoid !important;
            page-break-after: avoid !important;
            break-inside: avoid !important;
            break-after: avoid !important;
          }
          /* Fixed pixel heights — flex with min-height:0 was being
             ignored by iOS Safari's print engine, allowing the SVG
             to render at native size and overflow onto page 2.
             Hard-clamping each child means the SVG can NEVER exceed
             its allotted slice. Math: 11in page - 2×0.4in padding
             - 0.6in header - 0.3in footer - 0.1in gaps = 9.0in for
             the SVG wrap. We use 8.6in as a safety margin against
             iOS Safari's per-block padding leakage. */
          .cfp-print-header {
            display: block !important;
            height: 0.55in !important;
            max-height: 0.55in !important;
            margin: 0 !important;
            padding: 0 0 6px 0 !important;
            overflow: hidden !important;
            page-break-inside: avoid !important;
            break-inside: avoid !important;
          }
          .cfp-print-svg-wrap {
            display: flex !important;
            align-items: center !important;
            justify-content: center !important;
            width: 100% !important;
            height: 8.6in !important;
            max-height: 8.6in !important;
            margin: 0.05in 0 !important;
            overflow: hidden !important;
            page-break-inside: avoid !important;
            break-inside: avoid !important;
          }
          .cfp-print-svg-wrap svg {
            display: block !important;
            width: 7.6in !important;
            height: 8.5in !important;
            max-width: 7.6in !important;
            max-height: 8.5in !important;
          }
          .cfp-print-footer {
            display: flex !important;
            justify-content: space-between !important;
            height: 0.25in !important;
            max-height: 0.25in !important;
            margin: 0 !important;
            padding: 4px 0 0 0 !important;
            font-size: 9px !important;
            overflow: hidden !important;
            page-break-inside: avoid !important;
            break-inside: avoid !important;
          }
          .cfp-print-toolbar { display: none !important; }
        }
        body { background: #f4f4f4; margin: 0; }
        .cfp-print-root {
          font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
          color: #0f172a;
          /* Fluid on small screens, capped at letter width on tablets
             and desktop so the on-screen preview matches what the
             saved PDF will look like. The @media print branch above
             pins it to the exact letter usable area. */
          width: 100%;
          max-width: 7.5in;
          min-height: 100vh;
          margin: 0 auto;
          padding: 0 12px;
          box-sizing: border-box;
          display: flex;
          flex-direction: column;
        }
        .cfp-print-toolbar {
          display: flex;
          gap: 8px;
          padding: 12px 0;
          /* Honor the iOS notch / Dynamic-Island safe area so Back +
             Print stay tappable on every device. The :12px inner
             padding is in addition to the env() inset. */
          padding-top: max(12px, env(safe-area-inset-top));
          padding-left: max(12px, env(safe-area-inset-left));
          padding-right: max(12px, env(safe-area-inset-right));
          position: sticky;
          top: 0;
          background: #f4f4f4;
          z-index: 10;
        }
        .cfp-print-toolbar button {
          display: inline-flex; align-items: center; gap: 6px;
          padding: 8px 14px; border-radius: 9999px;
          font-size: 13px; font-weight: 700;
          cursor: pointer;
        }
        .cfp-print-back {
          background: #ffffff; color: #0f172a; border: 1px solid #cbd5e1;
        }
        .cfp-print-reprint {
          background: #fffaf0; color: #B8860B; border: 1px solid #B8860B;
        }
        .cfp-print-header {
          border-bottom: 2px solid #B8860B;
          padding-bottom: 12px;
          margin-bottom: 12px;
        }
        .cfp-print-header h1 {
          margin: 0;
          font-size: 20px;
          font-weight: 800;
          color: #B8860B;
          letter-spacing: 0.02em;
        }
        .cfp-print-header .subtitle {
          margin-top: 4px;
          font-size: 13px;
          color: #475569;
        }
        .cfp-print-svg-wrap {
          flex: 1;
          min-height: 0;
          display: flex;
          align-items: center;
          justify-content: center;
        }
        .cfp-print-svg-wrap svg {
          width: 100%;
          height: auto;
          max-height: 8.5in;
        }
        .cfp-print-footer {
          margin-top: 12px;
          padding-top: 8px;
          border-top: 1px solid #e2e8f0;
          font-size: 10px;
          color: #94a3b8;
          display: flex;
          justify-content: space-between;
        }
      `}</style>

      {/* Screen-only toolbar — gives the user an obvious escape route
          on iOS standalone PWA where the OS print dialog cancels and
          leaves them on this page. Hidden via @media print so the
          PDF stays clean. */}
      <div className="cfp-print-toolbar">
        <button
          type="button"
          className="cfp-print-back"
          onClick={() => navigate(-1)}
          data-testid="entity-print-back"
        >
          <ChevronLeft size={14} /> Back
        </button>
        <button
          type="button"
          className="cfp-print-reprint"
          onClick={() => { try { window.print(); } catch { /* user dismissed */ } }}
          data-testid="entity-print-reprint"
        >
          <Printer size={14} /> Print
        </button>
      </div>

      <div className="cfp-print-header">
        <h1>Entities &amp; Structures</h1>
        <div className="subtitle">
          {estateName ? `${estateName} • ` : ''}{today}
        </div>
      </div>

      <div className="cfp-print-svg-wrap">
        <svg
          viewBox={`${layout.viewBox.x} ${layout.viewBox.y} ${layout.viewBox.w} ${layout.viewBox.h}`}
          preserveAspectRatio="xMidYMid meet"
          xmlns="http://www.w3.org/2000/svg"
          data-testid="entity-print-svg"
        >
          {renderEdges()}
          {layout.tileRects.filter((r) => r.key !== '__legend__').map(renderTile)}
          {renderLegend()}
        </svg>
      </div>

      <div className="cfp-print-footer">
        <span>Generated by CarryOn™</span>
        <span>carryon.us</span>
      </div>
    </div>
  );
}

function truncate(s, n) {
  if (!s) return '';
  return s.length <= n ? s : s.slice(0, n - 1) + '…';
}
