/**
 * EntitiesPrintPage — letter-format printable view of the Entities &
 * Structures org chart.
 *
 * Opens in a new tab from the toolbar Print button. Renders a static
 * SVG (no React drag/zoom plumbing) so the browser's "Save as PDF"
 * pipeline produces a clean vector PDF that scales infinitely. Auto-
 * triggers `window.print()` once layout settles so the user lands on
 * the OS print dialog instantly.
 *
 * Page layout (letter / 8.5×11):
 *   ┌──────────────────────────────────────┐
 *   │  CarryOn™  — Entities & Structures   │  ← header
 *   │  Smith Family Trust • Mar 14, 2026   │
 *   ├──────────────────────────────────────┤
 *   │                                      │
 *   │        [centered SVG of tree]        │
 *   │                                      │
 *   ├──────────────────────────────────────┤
 *   │  Generated by CarryOn • carryon.us   │  ← footer
 *   └──────────────────────────────────────┘
 *
 * The SVG uses `viewBox` + `preserveAspectRatio="xMidYMid meet"` so it
 * fills the usable area of the page, centered, regardless of how
 * wide/tall the user's tree turned out. Legend is rendered as part of
 * the SVG so it prints at the same scale and at the position the user
 * dragged it to in the live chart.
 */
import React, { useEffect, useMemo, useState } from 'react';
import ReactDOM from 'react-dom';
import { useParams, useNavigate } from 'react-router-dom';
import axios from 'axios';
import { ChevronLeft, Printer } from 'lucide-react';
import { useAuth } from '../../contexts/AuthContext';
import { API_URL } from '../../config';
import {
  buildGraph,
  computeInitialLayout,
  routeEdge,
  polylineToRoundedPath,
  PRINT_TILE_DIMENSIONS,
} from '../../components/financial/entities/EntityOrgChart';
import {
  ROLE_PALETTE,
  ROLE_OPTIONS,
  BUCKETS as ENTITY_BUCKETS,
  getTypeMeta,
} from '../../config/entityCatalog';
import { LEGEND_W } from '../../components/financial/entities/EntityLegend';

const { ENTITY_W, ENTITY_H, PERSON_W, PERSON_H, CORNER_R } = PRINT_TILE_DIMENSIONS;

const EQUITY_ROLE_IDS = new Set([
  'owner', 'member', 'shareholder', 'gp', 'lp',
  'joint_tenant', 'tenant_in_common', 'community_property',
]);
const ROLE_LABEL = new Map(ROLE_OPTIONS.map((r) => [r.id, r.label]));

const fmtDate = (d = new Date()) =>
  d.toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' });

export default function EntitiesPrintPage() {
  const { estateId } = useParams();
  const navigate = useNavigate();
  const { user, getAuthHeaders } = useAuth();
  const [data, setData] = useState(null);
  const [estateName, setEstateName] = useState('');
  const [error, setError] = useState(null);

  // Fetch the chart payload (entities + people + relationships +
  // server-persisted overrides) plus the estate name for the header.
  useEffect(() => {
    let alive = true;
    (async () => {
      try {
        const headers = getAuthHeaders();
        const [entitiesRes, estateRes] = await Promise.all([
          axios.get(`${API_URL}/financial/entities/${estateId}`, headers),
          axios.get(`${API_URL}/estates/${estateId}`, headers).catch(() => ({ data: null })),
        ]);
        if (!alive) return;
        setData(entitiesRes.data || {});
        setEstateName(estateRes?.data?.name || '');
      } catch (e) {
        if (!alive) return;
        setError(e?.response?.data?.detail || e?.message || 'Could not load chart data');
      }
    })();
    return () => { alive = false; };
  }, [estateId, getAuthHeaders]);

  // Compute layout + bbox once data lands.
  const layout = useMemo(() => {
    if (!data) return null;
    const beneficiaries = []; // benefactor view → no extra benef nodes; relationships drive everything
    const graph = buildGraph({
      entities: data.entities || [],
      externals: data.external_people || [],
      relationships: data.relationships || [],
      beneficiaries,
      user,
    });
    const initial = computeInitialLayout(graph.nodes, graph.depth);
    const overrides = data.chart_layout || {};

    const positionOf = (key) => overrides[key] || initial.positions[key] || { x: 0, y: 0 };

    // Tile rects for the TREE only — legend is rendered as a
    // separate absolutely-positioned block (see the JSX below), so
    // it never participates in the tree's bounding box or its
    // viewBox math. This lets the tree center cleanly inside the
    // SVG while the legend pins to the page's top-right corner.
    const tileRects = graph.nodes.map((n) => {
      const p = positionOf(n.key);
      return { key: n.key, x: p.x, y: p.y, w: n.w, h: n.h, node: n };
    });

    // BBox covering every TREE tile with a comfortable stroke pad.
    const PAD = 24;
    let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
    tileRects.forEach((r) => {
      if (r.x < minX) minX = r.x;
      if (r.y < minY) minY = r.y;
      if (r.x + r.w > maxX) maxX = r.x + r.w;
      if (r.y + r.h > maxY) maxY = r.y + r.h;
    });
    if (!isFinite(minX)) { minX = minY = 0; maxX = 800; maxY = 600; }

    return {
      nodes: graph.nodes,
      edges: graph.edges,
      tileRects,
      viewBox: {
        x: minX - PAD,
        y: minY - PAD,
        w: (maxX - minX) + 2 * PAD,
        h: (maxY - minY) + 2 * PAD,
      },
      relationships: data.relationships || [],
      entities: data.entities || [],
    };
  }, [data, user]);

  // No auto-print: iOS Safari blocks programmatic window.print() that
  // isn't a direct response to a user tap, and re-rendering on memo
  // changes causes the "blocked from automatically printing" dialog
  // to re-pop forever. The user invokes printing via the Print chip
  // in the on-screen toolbar — that click IS a user gesture, so iOS
  // shows the share-sheet print UI cleanly with no warning.

  if (error) {
    return (
      <div style={{ padding: 32, fontFamily: 'system-ui, -apple-system, sans-serif', color: '#0f172a', background: '#ffffff', minHeight: '100vh' }}>
        <button
          type="button"
          onClick={() => navigate(-1)}
          style={{
            display: 'inline-flex', alignItems: 'center', gap: 6,
            padding: '8px 14px', borderRadius: 9999,
            border: '1px solid #B8860B', background: '#fffaf0',
            color: '#B8860B', fontSize: 13, fontWeight: 700, cursor: 'pointer',
            marginBottom: 16,
          }}
          data-testid="entity-print-back"
        >
          <ChevronLeft size={14} /> Back
        </button>
        <h1 style={{ marginTop: 0, fontSize: 20 }}>Could not generate print</h1>
        <p>{error}</p>
      </div>
    );
  }
  if (!layout) {
    return (
      <div style={{ padding: 32, fontFamily: 'system-ui, -apple-system, sans-serif', color: '#0f172a', background: '#ffffff', minHeight: '100vh' }}>
        <button
          type="button"
          onClick={() => navigate(-1)}
          style={{
            display: 'inline-flex', alignItems: 'center', gap: 6,
            padding: '8px 14px', borderRadius: 9999,
            border: '1px solid #B8860B', background: '#fffaf0',
            color: '#B8860B', fontSize: 13, fontWeight: 700, cursor: 'pointer',
            marginBottom: 16,
          }}
          data-testid="entity-print-back"
        >
          <ChevronLeft size={14} /> Back
        </button>
        Loading chart for printing…
      </div>
    );
  }

  const today = fmtDate();
  const presentRoles = (() => {
    const seen = new Set();
    layout.relationships.forEach((r) => { if (r.role) seen.add(r.role); });
    return ROLE_OPTIONS.filter((r) => seen.has(r.id));
  })();
  const presentCategories = (() => {
    const seen = new Set();
    layout.entities.forEach((e) => { if (e.category) seen.add(e.category); });
    return (ENTITY_BUCKETS || []).filter((b) => seen.has(b.id));
  })();

  // ── Static SVG renderer ──────────────────────────────────────────
  const rectByKey = Object.fromEntries(layout.tileRects.map((r) => [r.key, r]));

  const renderEdges = () => {
    return layout.edges.map((edge) => {
      const sR = rectByKey[edge.sourceKey];
      const tR = rectByKey[edge.targetKey];
      if (!sR || !tR) return null;
      const obstacles = layout.tileRects.filter((r) => r.key !== sR.key && r.key !== tR.key);
      const { points, midPoint } = routeEdge(sR, tR, obstacles, edge.id);
      const role = ROLE_PALETTE[edge.role] || ROLE_PALETTE.owner;
      const isEquity = EQUITY_ROLE_IDS.has(edge.role);
      const stroke = isEquity ? '#B8860B' : role.color;
      const sw = isEquity && edge.ownership_pct ? Math.max(1.6, Math.min(3.4, edge.ownership_pct / 33)) : 1.8;
      const d = polylineToRoundedPath(points);
      return (
        <g key={edge.id}>
          <path
            d={d}
            fill="none"
            stroke={stroke}
            strokeWidth={sw}
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeDasharray={role.dash || undefined}
            opacity={0.95}
          />
          {isEquity && edge.ownership_pct != null && (
            <g transform={`translate(${midPoint.x - 18}, ${midPoint.y - 9})`}>
              <rect width="36" height="18" rx="9" fill="#fffaf0" stroke="#B8860B" strokeWidth="1" />
              <text x="18" y="13" textAnchor="middle" fontSize="10" fontWeight="700" fill="#B8860B">
                {Math.round(edge.ownership_pct)}%
              </text>
            </g>
          )}
        </g>
      );
    });
  };

  const renderTile = (rect) => {
    const n = rect.node;
    if (!n) return null;
    const isEntity = n.kind === 'entity';
    const e = isEntity ? n.entity : null;
    const typeMeta = isEntity ? getTypeMeta(e.category, e.type) : null;
    const titleText = isEntity ? (e?.name || 'Entity') : (n.label || '');
    const subText = isEntity
      ? (typeMeta?.friendly || e?.type || '')
      : (n.sublabel || '');
    // Tile fills/strokes: gold-tinted, matching the live chart's
    // "premium" feel rather than the previous stark white-on-gray.
    const tileFill = isEntity ? '#FFFDF7' : '#FFFFFF';
    const tileStroke = '#B8860B';
    const tileStrokeW = 1.2;
    const avatarColor = n.avatar_color || '#B8860B';
    const avatarBg = n.kind === 'user' ? '#FEF3C7' : '#FFFFFF';
    const photoUrl = n.photo || null;
    const clipId = `print-avatar-clip-${n.key.replace(/[^a-zA-Z0-9]/g, '_')}`;
    return (
      <g key={n.key} transform={`translate(${rect.x}, ${rect.y})`}>
        {/* Tile background */}
        <rect
          width={rect.w}
          height={rect.h}
          rx={CORNER_R}
          fill={tileFill}
          stroke={tileStroke}
          strokeWidth={tileStrokeW}
        />
        {/* Entity tile: bucket icon dot (left), then title + sub */}
        {isEntity && (
          <>
            <circle cx={16} cy={rect.h / 2} r={6} fill={tileStroke} opacity={0.85} />
            <text
              x={32}
              y={rect.h / 2 - 4}
              fontSize={13}
              fontWeight="700"
              fill="#0F172A"
            >
              {truncate(titleText, 24)}
            </text>
            {subText && (
              <text
                x={32}
                y={rect.h / 2 + 12}
                fontSize={10}
                fontWeight="600"
                fill={tileStroke}
              >
                {truncate(subText, 28)}
              </text>
            )}
            {e?.formation_state && (
              <g transform={`translate(${32}, ${rect.h - 18})`}>
                <rect width="28" height="13" rx="6" fill="#FFFAF0" stroke={tileStroke} strokeWidth={0.9} />
                <text x="14" y="9.5" textAnchor="middle" fontSize="8" fontWeight="700" fill={tileStroke}>
                  {e.formation_state}
                </text>
              </g>
            )}
          </>
        )}
        {/* Person tile: avatar circle (with photo if present) + name + sub + role chips */}
        {!isEntity && (
          <>
            <defs>
              <clipPath id={clipId}>
                <circle cx={rect.w / 2} cy={28} r={22} />
              </clipPath>
            </defs>
            {/* Avatar ring */}
            <circle
              cx={rect.w / 2}
              cy={28}
              r={23}
              fill={avatarBg}
              stroke={avatarColor}
              strokeWidth={1.8}
            />
            {photoUrl ? (
              <image
                href={photoUrl}
                xlinkHref={photoUrl}
                x={rect.w / 2 - 22}
                y={6}
                width={44}
                height={44}
                preserveAspectRatio="xMidYMid slice"
                clipPath={`url(#${clipId})`}
              />
            ) : (
              <text
                x={rect.w / 2}
                y={33}
                textAnchor="middle"
                fontSize={14}
                fontWeight="700"
                fill="#92400E"
              >
                {((n.label?.[0] || '') + (n.sublabel?.[0] || '')).toUpperCase().slice(0, 2)}
              </text>
            )}
            {/* Name */}
            <text
              x={rect.w / 2}
              y={68}
              textAnchor="middle"
              fontSize={11}
              fontWeight="700"
              fill="#0F172A"
            >
              {truncate(titleText, 14)}
            </text>
            {subText && (
              <text
                x={rect.w / 2}
                y={82}
                textAnchor="middle"
                fontSize={9}
                fill="#475569"
              >
                {truncate(subText, 16)}
              </text>
            )}
            {Array.isArray(n.titles) && n.titles.length > 0 && (
              <text
                x={rect.w / 2}
                y={98}
                textAnchor="middle"
                fontSize={9}
                fontWeight="700"
                fill={tileStroke}
              >
                {truncate(n.titles.join(' · '), 18)}
              </text>
            )}
          </>
        )}
      </g>
    );
  };

  // Standalone legend block — rendered as its own small SVG outside
  // the main tree SVG and absolutely positioned to the top-right of
  // the page (see .cfp-print-legend in the CSS). Disassociated from
  // the tree per benefactor request: tree stays centered, legend
  // pins to the top-right corner.
  const renderLegend = () => {
    if (presentRoles.length === 0 && presentCategories.length === 0) return null;
    const headerH = 22;
    const rowH = 18;
    const nRows = presentRoles.length + presentCategories.length + (presentRoles.length && presentCategories.length ? 1 : 0);
    const computedH = Math.max(60, headerH + nRows * rowH + 14);
    return (
      <div className="cfp-print-legend" aria-hidden="true">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox={`0 0 ${LEGEND_W} ${computedH}`}
          width={LEGEND_W}
          height={computedH}
          style={{ display: 'block' }}
        >
          <rect
            width={LEGEND_W}
            height={computedH}
            rx={12}
            fill="#ffffff"
            stroke="#B8860B"
            strokeWidth={1.4}
          />
          <text x={10} y={16} fontSize={11} fontWeight="700" fill="#B8860B" letterSpacing="0.06em">
            LEGEND
          </text>
          <line x1={0} x2={LEGEND_W} y1={headerH} y2={headerH} stroke="#B8860B" strokeOpacity={0.35} />
          {presentRoles.map((role, i) => {
            const palette = ROLE_PALETTE[role.id] || ROLE_PALETTE.owner;
            const isEquity = EQUITY_ROLE_IDS.has(role.id);
            const stroke = isEquity ? '#B8860B' : palette.color;
            const y = headerH + 14 + i * rowH;
            return (
              <g key={role.id}>
                <line
                  x1={10} x2={42}
                  y1={y - 3} y2={y - 3}
                  stroke={stroke}
                  strokeWidth={isEquity ? 2.2 : 1.8}
                  strokeLinecap="round"
                  strokeDasharray={palette.dash || undefined}
                />
                <text x={50} y={y} fontSize={11} fill="#0f172a">{role.label}</text>
              </g>
            );
          })}
          {presentRoles.length > 0 && presentCategories.length > 0 && (
            <line
              x1={6} x2={LEGEND_W - 6}
              y1={headerH + 8 + presentRoles.length * rowH}
              y2={headerH + 8 + presentRoles.length * rowH}
              stroke="#B8860B"
              strokeOpacity={0.18}
            />
          )}
          {presentCategories.map((b, i) => {
            const yOffset = headerH + 14 + presentRoles.length * rowH + (presentRoles.length ? rowH : 0) + i * rowH;
            return (
              <g key={b.id}>
                <circle cx={26} cy={yOffset - 3} r={5} fill="#B8860B" />
                <text x={50} y={yOffset} fontSize={11} fill="#0f172a">{b.label}</text>
              </g>
            );
          })}
        </svg>
      </div>
    );
  };

  return ReactDOM.createPortal(
    <div className="cfp-print-root">
      <style>{`
        @page { size: letter portrait; margin: 0; }
        @media print {
          html, body {
            background: #ffffff !important;
            margin: 0 !important;
            padding: 0 !important;
            width: 8.5in !important;
            min-width: 8.5in !important;
            max-width: 8.5in !important;
            height: 10.0in !important;
            min-height: 0 !important;
            max-height: 10.0in !important;
            overflow: hidden !important;
          }
          /* The print root is rendered via React portal AS A DIRECT
             CHILD OF <body>. That lets us hide every OTHER body
             child cleanly — incl. NetworkStatusBanner, PendingSyncChip,
             NotificationContainer, and the entire #root mount — so
             nothing they render adds height to the print document. */
          body > *:not(.cfp-print-root) {
            display: none !important;
          }
          .cfp-print-root {
            color: #0f172a !important;
            display: block !important;
            position: relative !important;
            width: 8.5in !important;
            min-width: 8.5in !important;
            max-width: 8.5in !important;
            /* Sized to 8.5in × 9.5in inside an 11in page. Leaves
               ~1.5in of slack for iOS Safari's invisible "system"
               margin / its own header-footer chrome on every printed
               page — single-page output is guaranteed and the tree
               has enough vertical room to center properly between
               our header and the iOS footer. */
            height: 9.5in !important;
            min-height: 0 !important;
            max-height: 9.5in !important;
            padding: 0.3in !important;
            margin: 0 !important;
            box-sizing: border-box !important;
            overflow: hidden !important;
            page-break-inside: avoid !important;
            page-break-after: avoid !important;
            break-inside: avoid !important;
            break-after: avoid !important;
          }
          .cfp-print-root * {
            page-break-inside: avoid !important;
            page-break-after: avoid !important;
            break-inside: avoid !important;
            break-after: avoid !important;
          }
          .cfp-print-header {
            display: block !important;
            height: 0.65in !important;
            max-height: 0.65in !important;
            margin: 0 0 0.05in 0 !important;
            padding: 0 0 6px 0 !important;
            /* Override screen rule that put a 2px gold border on the
               bottom — it cut through the subtitle when squeezed into
               the print height. Use a thin gold rule INSIDE the
               header's allotted height instead. */
            border-bottom: 1px solid #B8860B !important;
            overflow: hidden !important;
          }
          .cfp-print-svg-wrap {
            display: flex !important;
            flex-direction: column !important;
            align-items: stretch !important;
            justify-content: stretch !important;
            width: 100% !important;
            /* Fills ALL the remaining vertical space below the header
               (root 9.5in - 0.6in padding - 0.65in header - 0.05in
               header bottom-margin = 8.2in). The SVG inside is a
               flex child with flex:1 so it grows to fill the wrap on
               every print engine (iOS Safari historically ignored
               height:100% on a non-flex block parent). */
            height: 8.2in !important;
            max-height: 8.2in !important;
            min-height: 8.2in !important;
            margin: 0 !important;
            overflow: hidden !important;
            position: relative !important;
          }
          .cfp-print-svg-wrap svg {
            display: block !important;
            flex: 1 1 auto !important;
            width: 100% !important;
            height: 100% !important;
            min-height: 0 !important;
          }
          /* Legend pinned to the absolute BOTTOM-RIGHT corner of the
             print page, above the iOS-rendered footer. Scales as a
             fraction of the page width (not a fixed pixel size) so
             it works for any legend content length and any future
             page-size change. The inner SVG keeps its aspect ratio. */
          .cfp-print-legend {
            position: absolute !important;
            bottom: 0.15in !important;
            right: 0.15in !important;
            top: auto !important;
            left: auto !important;
            width: 22% !important;
            max-width: 2.0in !important;
            min-width: 1.4in !important;
            margin: 0 !important;
            padding: 0 !important;
            pointer-events: none !important;
          }
          .cfp-print-legend svg {
            width: 100% !important;
            height: auto !important;
            display: block !important;
          }
          /* iOS Safari automatically renders its OWN header (URL) and
             footer (date + page number) on every printed page. Hiding
             our in-document footer avoids the duplicate-footer
             appearance the user reported. */
          .cfp-print-footer { display: none !important; }
          .cfp-print-toolbar { display: none !important; }
        }
        body { background: #f4f4f4; margin: 0; }
        .cfp-print-root {
          font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
          color: #0f172a;
          /* Fluid on small screens, capped at letter width on tablets
             and desktop so the on-screen preview matches what the
             saved PDF will look like. The @media print branch above
             pins it to the exact letter usable area. */
          width: 100%;
          max-width: 7.5in;
          /* Use dynamic-viewport-height so the layout fits the *real*
             visible area on iOS Safari/PWA (where the URL bar and
             home-indicator eat into 100vh). Falls back to 100vh for
             browsers that don't support dvh. */
          min-height: 100vh;
          min-height: 100dvh;
          height: 100vh;
          height: 100dvh;
          margin: 0 auto;
          padding: 0 12px;
          padding-bottom: max(12px, env(safe-area-inset-bottom));
          box-sizing: border-box;
          display: flex;
          flex-direction: column;
          position: relative;
          overflow: hidden;
        }
        .cfp-print-legend {
          position: absolute;
          /* True bottom-right corner of the on-screen preview frame,
             just above the in-document footer. Width scales as a
             fraction of the print-root width (clamped so it never
             becomes tiny on a phone or oversized on a 4K monitor). */
          bottom: calc(36px + env(safe-area-inset-bottom, 0px));
          right: 12px;
          width: clamp(140px, 24%, 220px);
          z-index: 5;
          pointer-events: none;
        }
        .cfp-print-legend svg {
          width: 100%;
          height: auto;
          display: block;
          filter: drop-shadow(0 2px 6px rgba(15, 23, 42, 0.08));
        }
        .cfp-print-toolbar {
          display: flex;
          gap: 8px;
          padding: 12px 0;
          /* Honor the iOS notch / Dynamic-Island safe area so Back +
             Print stay tappable on every device. The :12px inner
             padding is in addition to the env() inset. */
          padding-top: max(12px, env(safe-area-inset-top));
          padding-left: max(12px, env(safe-area-inset-left));
          padding-right: max(12px, env(safe-area-inset-right));
          position: sticky;
          top: 0;
          background: #f4f4f4;
          z-index: 10;
        }
        .cfp-print-toolbar button {
          display: inline-flex; align-items: center; gap: 6px;
          padding: 8px 14px; border-radius: 9999px;
          font-size: 13px; font-weight: 700;
          cursor: pointer;
        }
        .cfp-print-back {
          background: #ffffff; color: #0f172a; border: 1px solid #cbd5e1;
        }
        .cfp-print-reprint {
          background: #fffaf0; color: #B8860B; border: 1px solid #B8860B;
        }
        .cfp-print-header {
          border-bottom: 2px solid #B8860B;
          padding-bottom: 12px;
          margin-bottom: 12px;
        }
        .cfp-print-header h1 {
          margin: 0;
          font-size: 20px;
          font-weight: 800;
          color: #B8860B;
          letter-spacing: 0.02em;
        }
        .cfp-print-header .subtitle {
          margin-top: 4px;
          font-size: 13px;
          color: #475569;
        }
        .cfp-print-svg-wrap {
          flex: 1 1 auto;
          min-height: 0;
          width: 100%;
          display: block;
          position: relative;
        }
        .cfp-print-svg-wrap svg {
          width: 100%;
          height: 100%;
          display: block;
        }
        .cfp-print-footer {
          margin-top: 12px;
          padding-top: 8px;
          border-top: 1px solid #e2e8f0;
          font-size: 10px;
          color: #94a3b8;
          display: flex;
          justify-content: space-between;
        }
      `}</style>

      {/* Screen-only toolbar — gives the user an obvious escape route
          on iOS standalone PWA where the OS print dialog cancels and
          leaves them on this page. Hidden via @media print so the
          PDF stays clean. */}
      <div className="cfp-print-toolbar">
        <button
          type="button"
          className="cfp-print-back"
          onClick={() => navigate(-1)}
          data-testid="entity-print-back"
        >
          <ChevronLeft size={14} /> Back
        </button>
        <button
          type="button"
          className="cfp-print-reprint"
          onClick={() => { try { window.print(); } catch { /* user dismissed */ } }}
          data-testid="entity-print-reprint"
        >
          <Printer size={14} /> Print
        </button>
      </div>

      <div className="cfp-print-header">
        <h1>Entities &amp; Structures</h1>
        <div className="subtitle">
          {estateName ? `${estateName} • ` : ''}{today}
        </div>
      </div>

      <div className="cfp-print-svg-wrap">
        <svg
          width="756"
          height="787"
          viewBox={`${layout.viewBox.x} ${layout.viewBox.y} ${layout.viewBox.w} ${layout.viewBox.h}`}
          preserveAspectRatio="xMidYMid meet"
          xmlns="http://www.w3.org/2000/svg"
          data-testid="entity-print-svg"
          style={{ display: 'block' }}
        >
          {renderEdges()}
          {layout.tileRects.map(renderTile)}
        </svg>
        {renderLegend()}
      </div>

      <div className="cfp-print-footer">
        <span>Generated by CarryOn™</span>
        <span>carryon.us</span>
      </div>
    </div>,
    document.body
  );
}

function truncate(s, n) {
  if (!s) return '';
  return s.length <= n ? s : s.slice(0, n - 1) + '…';
}
